// Source: trinity/trinity/Eve/SpaceObject/Children/EveChildBulletStorm.h
// Generated by format-carbon carbon-class --emit. Verify against eve/perObjectData/EveChildBulletStormPerObjectData.json.
import { type } from "#schema";
import { CjsModel } from "#model";
import { mat4 } from "#math/mat4";
import { vec4 } from "#math/vec4";

/** EveChildBulletStormPerObjectData (eve/perObjectData) - generated from schema shapeHash 49346bb7.... */
@type.define({ className: "EveChildBulletStormPerObjectData", family: "eve/perObjectData" })
export class EveChildBulletStormPerObjectData extends CjsModel
{

  /** m_worldTransform (Matrix) */
  @type.mat4
  worldTransform = mat4.create();

  /** m_effectInfo (Vector4) */
  @type.vec4
  effectInfo = vec4.create();

  /** m_targetPositionsWS (Vector4[TARGET_POSITION_COUNT]) */
  @type.array("vec4")
  targetPositionsWS = Array.from(
    { length: EveChildBulletStormPerObjectData.TARGET_POSITION_COUNT },
    () => vec4.create()
  );

  /**
   * EveChildBulletStorm.h:29 - `Vector4 m_targetPositionsWS[10]`. The bound is a
   * bare literal in Carbon, not a named constant.
   */
  static TARGET_POSITION_COUNT = 10;

}
