// Source: trinity/trinity/Eve/SpaceObject/Attachments/EveSpaceObjectDecal.h
// Generated by format-carbon carbon-class --emit. Verify against eve/perObjectData/EveDecalPerObjectData.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** EveDecalPerObjectData (eve/perObjectData) - generated from schema shapeHash 8d1f094d.... */
@type.define({ className: "EveDecalPerObjectData", family: "eve/perObjectData" })
export class EveDecalPerObjectData extends CjsModel
{

  /** m_vsData (DecalVSPerObjectData) */
  @type.rawStruct("DecalVSPerObjectData")
  vsData = null;

  /** m_psData (DecalPSPerObjectData) */
  @type.rawStruct("DecalPSPerObjectData")
  psData = null;

}
