// Quarantined legacy class; maintained turret constant layouts are RawData records.
//   trinity/trinity/Eve/Turret/EveTurretSet.h
// Generated by format-carbon carbon-class --emit. Verify against eve/attachment/turrets/EveTurretSetPSData.json.
import { type } from "#schema";
import { CjsModel } from "#model";
import { vec3 } from "#math/vec3";
import { vec4 } from "#math/vec4";

/** Represents the retired turret pixel-stage payload for ship, clip, radius, and spherical-harmonic lighting values now written through RawData. */
@type.define({ className: "EveTurretSetPSData", family: "eve/attachment/turrets" })
export class EveTurretSetPSData extends CjsModel
{

  /** m_shipData (Vector4) */
  @type.vec4
  shipData = vec4.create();

  /** m_clipData1 (Vector4) */
  @type.vec4
  clipData1 = vec4.create();

  /** m_clipRadius2Sq (float) */
  @type.float32
  clipRadius2Sq = 0;

  /** m_unused (Vector3) */
  @type.vec3
  unused = vec3.create();

  /** m_shLightingCoefficients (Vector4[SH_COEFFICIENT_COUNT]) */
  @type.array("vec4")
  shLightingCoefficients = Array.from(
    { length: EveTurretSetPSData.SH_COEFFICIENT_COUNT },
    () => vec4.create()
  );

  /** Tr2ShLightingManager.h:51 - `PACKED_COEFFICIENT_COUNT`. */
  static SH_COEFFICIENT_COUNT = 7;

}
