// Source: trinity/trinity/Eve/Turret/EveTurretSet.h
// Generated by format-carbon carbon-class --emit. Verify against eve/perObjectData/EveTurretSetPerObjectData.json.
import { type } from "#schema";
import { CjsModel } from "#model";
import { EveTurretSetPSData } from "./EveTurretSetPSData.js";
import { EveTurretSetVSData } from "./EveTurretSetVSData.js";

/** Represents the retired turret wrapper that paired vertex- and pixel-stage payloads before its producer returned RawData stage records. */
@type.define({ className: "EveTurretSetPerObjectData", family: "eve/perObjectData" })
export class EveTurretSetPerObjectData extends CjsModel
{

  /** m_vsData (EveTurretSetVSData) */
  @type.rawStruct("EveTurretSetVSData")
  vsData = new EveTurretSetVSData();

  /** m_psData (EveTurretSetPSData) */
  @type.rawStruct("EveTurretSetPSData")
  psData = new EveTurretSetPSData();

}
