// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Interior/Tr2InteriorConstantBufferFormats.h
// Generated by format-carbon carbon-class --emit. Verify against interior/Tr2InteriorPerObjectVSData.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { mat4 } from "@carbonenginejs/runtime-utils/mat4";
import { vec2 } from "@carbonenginejs/runtime-utils/vec2";
import { vec4 } from "@carbonenginejs/runtime-utils/vec4";

/** Per-object interior vertex-stage data containing world and UV transforms. */
@type.define({ className: "Tr2InteriorPerObjectVSData", family: "interior" })
export class Tr2InteriorPerObjectVSData extends CjsModel
{

  /** WorldMat (Matrix) */
  @type.mat4
  WorldMat = mat4.create();

  /** uvLinearTransform (Vector4) */
  @type.vec4
  uvLinearTransform = vec4.create();

  /** uvTranslation (Vector2) */
  @type.vec2
  uvTranslation = vec2.create();

  /** padding (Vector2) */
  @type.vec2
  padding = vec2.create();

}
