// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Interior/Tr2InteriorConstantBufferFormats.h
// Generated by format-carbon carbon-class --emit. Verify against interior/Tr2PerObjectParticleVSData.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { mat4 } from "@carbonenginejs/runtime-utils/mat4";

/**
 * Per-object particle vertex-stage data containing world and inverse-view
 * matrices.
 */
@type.define({ className: "Tr2PerObjectParticleVSData", family: "interior" })
export class Tr2PerObjectParticleVSData extends CjsModel
{

  /** WorldMat (Matrix) */
  @type.mat4
  WorldMat = mat4.create();

  /** InvViewMat (Matrix) */
  @type.mat4
  InvViewMat = mat4.create();

}
