// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObject/Children/Behaviors/SplineTunnelGroup.h
//   trinity/trinity/Eve/SpaceObject/Children/Behaviors/SplineTunnelGroup.cpp
// Generated by format-carbon carbon-class --emit. Verify against eve/child/behaviors/SplineTunnelGroup.json.
import { carbon, impl, io, schema, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { mat4 } from "@carbonenginejs/runtime-utils/mat4";
import { vec3 } from "@carbonenginejs/runtime-utils/vec3";
import {
  BELIST_EVENTMASK,
  BELIST_INSERTED,
  BELIST_LOADFINISHED,
  BELIST_REMOVED
} from "../../../../controllers/contracts.js";
import { TunnelGroupType } from "../enums.js";
import { SplineTunnel } from "./SplineTunnel.js";
import { SplineTunnelPoint } from "./SplineTunnelPoint.js";

const DEBUG_TRANSFORM = mat4.create();
const DEBUG_START = vec3.create();
const DEBUG_END = vec3.create();

/** SplineTunnelGroup (eve/child/behaviors) - generated from schema shapeHash da595535.... */
@type.define({ className: "SplineTunnelGroup", family: "eve" })
export class SplineTunnelGroup extends CjsModel
{
  static TunnelGroupType = TunnelGroupType;

  /** CPU spline tunnel records rebuilt from the authored curve sets. */
  tunnels = [];

  /** m_tunnelGroupType (TunnelGroupType - enum TunnelGroupType) [READWRITE, PERSIST, NOTIFY, ENUM] */
  @io.notify
  @io.persist
  @type.int32
  @schema.enum("TunnelGroupType")
  tunnelGroupType = 2;

  /** m_curveSets (PTr2CurveVector3Vector) [READ, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.list("Tr2CurveVector3")
  curveSets = [];

  /** m_numBreakPoints (int32_t) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.int32
  breakPoints = 2;

  /** m_tunnelWidth (float) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.float32
  tunnelWidth = 15;

  /** m_entrancePullSize (float) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.float32
  entrancePullSize = 50;

  /** m_entrySize (float) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.float32
  entrySize = 20;

  // Owner callback into the system/behavior tunnel registry (Carbon
  // m_changeSystemTunnelRegistry) and its debug color.
  #changeSystemTunnelRegistry = null;

  #debugColor = 0xffffff00;

  // Re-entrancy guard: the registry callback may ask for the tunnels while
  // they are being rebuilt.
  #creatingTunnels = false;

  /** Carbon SplineTunnelGroup::GetTunnelGroupType (cpp:24-27). */
  @carbon.method
  @impl.implemented
  GetTunnelGroupType()
  {
    return this.tunnelGroupType;
  }

  /**
   * Stores the owner's tunnel-registry callback and debug color, then
   * rebuilds the tunnels (Carbon SetSystemTunnelFunctionReferenceAndColor,
   * cpp:30-35).
   * @param {Function} callback
   * @param {Number} color - debug color (retained for parity; debug rendering is omitted)
   */
  @carbon.method
  @impl.implemented
  SetSystemTunnelFunctionReferenceAndColor(callback, color = 0xffffff00)
  {
    this.#changeSystemTunnelRegistry = typeof callback === "function" ? callback : null;
    this.#debugColor = color >>> 0;
    this.createSplineTunnels();
  }

  /** Carbon method createSplineTunnels -> CreateSplineTunnels (cpp:37-79). */
  @carbon.method
  @carbon.renamed("createSplineTunnels")
  @impl.adapted
  @impl.reason("Samples portable vector curves into CPU tunnel records and reports registry changes through an injected callback.")
  createSplineTunnels()
  {
    if (this.#creatingTunnels)
    {
      return this.tunnels;
    }
    this.#creatingTunnels = true;
    try
    {
      this.tunnels.length = 0;
      const breakPoints = this.GetNumBreakPoints();
      for (const curve of this.curveSets)
      {
        if (!curve?.Length || !curve?.GetValue)
        {
          continue;
        }
        const duration = curve.Length();
        const step = duration / (breakPoints + 1);
        const positions = [];
        for (let index = 0; index < breakPoints + 2; index++)
        {
          const out = vec3.create();
          positions.push(curve.GetValue(index * step, out) ?? out);
        }

        const tunnel = new SplineTunnel();
        for (let index = 0; index < positions.length; index++)
        {
          const point = new SplineTunnelPoint();
          vec3.copy(point.pos, positions[index]);
          const previous = index === positions.length - 1 ? positions[index - 1] : positions[index];
          const next = index === positions.length - 1 ? positions[index] : positions[index + 1];
          vec3.subtract(point.rot, next, previous);
          tunnel.splinePoints.push(point);
        }
        tunnel.cylWidth = this.tunnelWidth;
        tunnel.pullSize = this.entrancePullSize;
        tunnel.pointOfNoReturnSize = this.entrySize;
        tunnel.tunnelGroupType = this.tunnelGroupType;
        this.tunnels.push(tunnel);
      }
    }
    finally
    {
      this.#creatingTunnels = false;
    }
    this.#changeSystemTunnelRegistry?.();
    return this.tunnels;
  }

  /** Carbon SplineTunnelGroup::OnListModified. */
  @carbon.method
  @impl.implemented
  OnListModified(event, _key = 0, _key2 = 0, _value = null, list = null)
  {
    if (list !== this.curveSets) return;
    const maskedEvent = Number(event) & BELIST_EVENTMASK;
    if ([BELIST_INSERTED, BELIST_REMOVED, BELIST_LOADFINISHED].includes(maskedEvent))
    {
      this.createSplineTunnels();
    }
  }

  /**
   * Returns the tunnel records (Carbon GetTunnels, cpp:81-84), building them
   * lazily when curves are present - the JS load path has no Blue notify to
   * trigger the first CreateSplineTunnels.
   */
  @carbon.method
  @impl.adapted
  @impl.reason("Lazily builds the tunnels on first access because the Blue curve-set list notify does not exist in JS.")
  GetTunnels()
  {
    if (this.tunnels.length === 0 && this.curveSets.length !== 0 && !this.#creatingTunnels)
    {
      this.createSplineTunnels();
    }
    return this.tunnels;
  }

  /** Carbon SplineTunnelGroup::GetCurveSets (cpp:86-89). */
  @carbon.method
  @impl.implemented
  GetCurveSets()
  {
    return this.curveSets;
  }

  /** Carbon SplineTunnelGroup::SetNumBreakPoints (cpp:91-94). */
  @carbon.method
  @impl.implemented
  SetNumBreakPoints(value)
  {
    this.breakPoints = Number(value) | 0;
  }

  /** Carbon SplineTunnelGroup::GetNumBreakPoints (cpp:96-99). */
  @carbon.method
  @impl.implemented
  GetNumBreakPoints()
  {
    return Math.max(this.breakPoints, 0);
  }

  /** Carbon SplineTunnelGroup::Initialize (cpp:104-107). */
  @carbon.method
  @impl.implemented
  Initialize()
  {
    this.createSplineTunnels();
    return true;
  }

  /** Carbon SplineTunnelGroup::OnModified (cpp:112-117): any property change
   * rebuilds the tunnels. */
  @carbon.method
  @impl.implemented
  OnModified(_value = null)
  {
    this.createSplineTunnels();
    return true;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Tr2DebugRendererOptions is represented by an injected Set-like option bag.")
  GetDebugOptions(options = new Set())
  {
    if (options?.add) options.add("SplineTunnels");
    else options?.insert?.("SplineTunnels");
    return options;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Emits Carbon's tunnel primitives through an injected ITr2DebugRenderer2-compatible capability.")
  RenderDebugInfo(renderer, parentWorldLocation = mat4.create())
  {
    for (const tunnel of this.tunnels)
    {
      const points = tunnel?.splinePoints ?? [];
      if (!points.length) continue;
      const first = points[0];
      const last = points[points.length - 1];
      mat4.translate(DEBUG_TRANSFORM, parentWorldLocation, first.pos);
      renderer?.DrawSphere?.(this, DEBUG_TRANSFORM, tunnel.pullSize, 6, 0, 0xff551111);
      renderer?.DrawSphere?.(this, DEBUG_TRANSFORM, tunnel.pointOfNoReturnSize, 6, 0, 0xff551111);
      mat4.translate(DEBUG_TRANSFORM, parentWorldLocation, last.pos);
      renderer?.DrawSphere?.(this, DEBUG_TRANSFORM, 5, 6, 0, 0xff335555);
      for (const point of points)
      {
        mat4.translate(DEBUG_TRANSFORM, parentWorldLocation, point.pos);
        renderer?.DrawSphere?.(this, DEBUG_TRANSFORM, tunnel.cylWidth, 6, 0, 0xff555555);
        vec3.add(DEBUG_END, point.pos, point.rot);
        vec3.transformMat4(DEBUG_START, point.pos, parentWorldLocation);
        vec3.transformMat4(DEBUG_END, DEBUG_END, parentWorldLocation);
        renderer?.DrawCylinder?.(this, DEBUG_START, DEBUG_END, tunnel.cylWidth, 8, 0, this.#debugColor);
      }
    }
  }

}
