// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Tr2GStateParameter.h
// Generated by format-carbon carbon-class --emit. Verify against trinityCore/Tr2GStateParameter.json.
import { carbon, impl, io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2GStateParameter (trinityCore) - generated from schema shapeHash cb552923.... */
@type.define({ className: "Tr2GStateParameter", family: "trinityCore" })
export class Tr2GStateParameter extends CjsModel
{

  /** m_name (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_value (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  value = 0;

  /** m_nodeName (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  nodename = "";

  /** Carbon method GetName (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  GetName()
  {
    return this.name;
  }

  /** Carbon method GetNodeName (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  GetNodeName()
  {
    return this.nodename;
  }

  /** Carbon method GetValue (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  GetValue()
  {
    return this.value;
  }

  /** Carbon method SetName (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  SetName(name)
  {
    this.name = String(name ?? "");
  }

  /** Carbon method SetNodeName (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  SetNodeName(name)
  {
    this.nodename = String(name ?? "");
  }

  /** Carbon method SetValue (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  SetValue(value)
  {
    this.value = Number(value);
  }

  @carbon.method
  @impl.implemented
  Initialize()
  {
    return true;
  }

}
