import assert from "node:assert/strict";
import test from "node:test";
import { blue } from "../../npm/dist/global/blue/index.js";
import { CJS_ENUM_NAME } from "../../npm/dist/global/blue/enums/CjsBlueEnumRegistry.js";

// Existing public definitions and class-static aliases must acquire the name
// used by schema without copying values or adding a JSON-visible member.
const definitions = [
  [
    "sof/faction/EveSOFDataFactionColorSet.js",
    "trinity.SOFDataFactionColorChooser.ColorType",
    "EveSOFDataFactionColorSet.ColorType"
  ],
  [
    "sof/hull/EveSOFDataHull.js",
    "trinity.EveSOFDataHull.BuildClass",
    "EveSOFDataHull.BuildClass"
  ],
  [
    "sof/hull/EveSOFDataHull.js",
    "trinity.EveSOFDataHull.ImpactEffectType",
    "EveSOFDataHull.ImpactEffectType"
  ],
  [
    "sof/hull/EveSOFDataHullBanner.js",
    "trinity.EveSOFDataHullBanner.Usage",
    "EveSOFDataHullBanner.Usage"
  ],
  [
    "sof/hull/EveSOFDataHullBannerSetItem.js",
    "trinity.EveSOFDataHullBannerSetItem.Usage",
    "EveSOFDataHullBannerSetItem.Usage"
  ],
  [
    "sof/hull/EveSOFDataHullDecalSetItem.js",
    "trinity.EveSOFDataHullDecalSetItem.Usage",
    "EveSOFDataHullDecalSetItem.Usage"
  ],
  [
    "sof/hull/EveSOFDataHullHazeSet.js",
    "trinity.EveSOFDataHullHazeSet.HazeType",
    "EveSOFDataHullHazeSet.HazeType"
  ],
  [
    "sof/hull/EveSOFDataHullPlaneSet.js",
    "trinity.EveSOFDataHullPlaneSet.Usage",
    "EveSOFDataHullPlaneSet.Usage"
  ],
  [
    "sof/layout/EveSOFDataHullExtensionPlacementDistributionMapGraphicSettings.js",
    "trinity.EveSOFDataHullExtensionPlacementDistributionMapGraphicSettings.DisplayQualityModifier",
    "EveSOFDataHullExtensionPlacementDistributionMapGraphicSettings.DisplayQualityModifier"
  ],
  [
    "sof/pattern/EveSOFDataPatternLayer.js",
    "trinity.EveSOFDataPatternLayer.ProjectionType",
    "EveSOFDataPatternLayer.ProjectionType"
  ],
  [
    "sof/pattern/EveSOFDataPatternLayer.js",
    "trinity.EveSOFDataPatternLayer.MaterialSource",
    "EveSOFDataPatternLayer.MaterialSource"
  ],
  [
    "sof/pattern/EveSOFDataPatternLayerProperties.js",
    "trinity.EveSOFDataPatternLayerProperties.ProjectionType",
    "EveSOFDataPatternLayerProperties.ProjectionType"
  ],
  [
    "sof/shared/EveSOFDataArea.js",
    "trinity.EveSOFDataArea.AreaType",
    "EveSOFDataArea.AreaType"
  ],
  [
    "sof/shared/EveSOFDataBlinkType.js",
    "trinity.EveSOFDataBlinkType.BlinkType",
    "EveSOFDataBlinkType.BlinkType"
  ],
  [
    "sof/shared/EveSOFDataInstancedMesh.js",
    "trinity.EveSOFDataInstancedMesh.DisplayQualityModifier",
    "EveSOFDataInstancedMesh.DisplayQualityModifier"
  ],
  [
    "sof/shared/EveSOFDataLogoSet.js",
    "trinity.EveSOFDataLogoSet.LogoType",
    "EveSOFDataLogoSet.LogoType"
  ],
  [
    "trinity/controllers/enums.js",
    "trinity.Tr2ActionPlayMeshAnimation.PlayAction",
    "PlayAction"
  ],
  [
    "trinity/controllers/enums.js",
    "trinity.Tr2ActionPlayMeshAnimation.StopAction",
    "StopAction"
  ],
  [
    "trinity/controllers/enums.js",
    "trinity.Tr2ActionPlayMeshAnimation.DestinationType",
    "DestinationType"
  ],
  [
    "trinity/controllers/enums.js",
    "trinity.Tr2ActionResetClipSphereCenter.ResetBehavior",
    "ResetBehavior"
  ],
  [
    "trinity/controllers/enums.js",
    "trinity.Tr2ControllerFloatVariable.Type",
    "Type"
  ],
  [
    "trinity/core/device/TriDevice.js",
    "trinity.TriDevice.DeviceType",
    "TriDevice.DeviceType"
  ],
  [
    "trinity/core/lighting/Tr2ShLightingManager.js",
    "trinity.Tr2ShLightingManager.Quality",
    "Tr2ShLightingManager.Quality"
  ],
  [
    "trinity/core/mesh/Tr2InstancedMesh.js",
    "trinity.Tr2InstancedMesh.BoundsMethod",
    "Tr2InstancedMesh.BoundsMethod"
  ],
  [
    "trinity/core/Tr2ReflectionProbe.js",
    "trinity.Tr2ReflectionProbe.ReflectionProbeRenderFrequency",
    "Tr2ReflectionProbe.ReflectionProbeRenderFrequency"
  ],
  [
    "trinity/core/Tr2ShadowMap.js",
    "trinity.Tr2ShadowMap.ShadowSplitMode",
    "Tr2ShadowMap.ShadowSplitMode"
  ],
  [
    "trinity/core/variable/Tr2ExpressionTermInfo.js",
    "trinity.Tr2ExpressionTermInfo.TermType",
    "Tr2ExpressionTermInfo.TermType"
  ],
  [
    "trinity/curves/enums.js",
    "trinity.Tr2CurveExtrapolation",
    "Tr2CurveExtrapolation"
  ],
  [
    "trinity/curves/enums.js",
    "trinity.Tr2CurveInterpolation",
    "Tr2CurveInterpolation"
  ],
  [
    "trinity/curves/enums.js",
    "trinity.Tr2CurveTangentType",
    "Tr2CurveTangentType"
  ],
  [
    "trinity/curves/enums.js",
    "trinity.Tr2CurveVector3LerpKeyInterpolation",
    "Tr2CurveVector3LerpKeyInterpolation"
  ],
  [
    "trinity/curves/enums.js",
    "trinity.Tr2FollowCurveKeyInterpolation",
    "Tr2FollowCurveKeyInterpolation"
  ],
  [
    "trinity/curves/enums.js",
    "trinity.Tr2ObjectFollowCurveKey.RotationSetting",
    "RotationSetting"
  ],
  [
    "trinity/eve/attachment/EveSpaceObjectAttachmentUtils.js",
    "trinity.FadeType",
    "FadeType"
  ],
  [
    "trinity/eve/attachment/turrets/EveTurretSet.js",
    "trinity.EveTurretSet.LOD",
    "EveTurretSet.LOD"
  ],
  [
    "trinity/eve/attachment/turrets/EveTurretSet.js",
    "trinity.EveTurretSet.State",
    "EveTurretSet.State"
  ],
  [
    "trinity/eve/attachment/turrets/EveTurretTarget.js",
    "trinity.ImpactBehaviour",
    "EveTurretTarget.ImpactBehaviour"
  ],
  [
    "trinity/eve/child/behaviors/enums.js",
    "trinity.BackAndForth.LocatorType",
    "LocatorType"
  ],
  [
    "trinity/eve/child/behaviors/enums.js",
    "trinity.IBehavior.ProcessPriority",
    "ProcessPriority"
  ],
  [
    "trinity/eve/child/behaviors/enums.js",
    "trinity.SplineTunnelGroup.TunnelGroupType",
    "TunnelGroupType"
  ],
  [
    "trinity/eve/child/behaviors/enums.js",
    "trinity.EveKDdroneManagementTree.PlaneType",
    "PlaneType"
  ],
  [
    "trinity/eve/child/EveChildContainer.js",
    "trinity.EveChildContainer.DisplayQualityModifier",
    "EveChildContainer.DisplayQualityModifier"
  ],
  [
    "trinity/eve/child/EveChildLineSet.js",
    "trinity.EveChildLineSet.lineSetType",
    "EveChildLineSet.lineSetType"
  ],
  [
    "trinity/eve/lights/Tr2Light.js",
    "trinity.Tr2Light.LIGHT_TYPE",
    "Tr2Light.LightType"
  ],
  [
    "trinity/eve/spaceObject/EveSpaceObject2.js",
    "trinity.EveSpaceObject2.LocatorType",
    "EveSpaceObject2.LocatorType"
  ],
  [
    "trinity/eve/ui/EveConnector.js",
    "trinity.EveConnector.ConnectorType",
    "EveConnector.ConnectorType"
  ],
  [
    "trinity/particle/element/Tr2ParticleElementData.js",
    "trinity.Tr2ParticleElementData.BufferType",
    "Tr2ParticleElementData.BufferType"
  ],
  [
    "trinity/particle/element/Tr2ParticleElementDeclarationName.js",
    "trinity.Tr2ParticleElementDeclarationName.Type",
    "Tr2ParticleElementDeclarationName.Type"
  ],
  [
    "trinity/postProcess/effect/Tr2PPDepthOfFieldEffect.js",
    "trinity.Tr2Bokeh.Shape",
    "Tr2PPDepthOfFieldEffect.Shape"
  ],
  [
    "trinity/postProcess/effect/Tr2PPTaaEffect.js",
    "trinity.Tr2PPTaaEffect.Quality",
    "Tr2PPTaaEffect.Quality"
  ]
];
for (const [file, name, exported] of definitions)
test("definition-site enum identity: " + name, async () =>
{
  const module = await import("../../npm/dist/" + file);
  let values = module;
  for (const member of exported.split(".")) values = values[member];
  assert.equal(typeof values, "object");
  assert.equal(blue.enums.Get(name), values);
  const property = Object.getOwnPropertyDescriptor(values, CJS_ENUM_NAME);
  assert.equal(property?.value, name);
  assert.equal(property.enumerable, false);
  assert.equal(Object.isFrozen(values), true);
  const persisted = JSON.parse(JSON.stringify(values));
  assert.deepEqual(Object.keys(persisted), Object.keys(values));
  assert.ok(Object.values(persisted).every(Number.isInteger));
});
