// Source: trinity/trinityal/Tr2RenderContextEnum.h (PixelFormat, DepthStencilFormat)
// Source: trinity/shadercompiler/EffectData.h (TextureType)

/** Carbon numeric GPU pixel formats (distinct from the abstract graphics/pixelFormats string vocabulary). */
export const PixelFormat = Object.freeze({
    PIXEL_FORMAT_UNKNOWN: 0,
    PIXEL_FORMAT_R32G32B32A32_TYPELESS: 1,
    PIXEL_FORMAT_R32G32B32A32_FLOAT: 2,
    PIXEL_FORMAT_R32G32B32A32_UINT: 3,
    PIXEL_FORMAT_R32G32B32A32_SINT: 4,
    PIXEL_FORMAT_R32G32B32_TYPELESS: 5,
    PIXEL_FORMAT_R32G32B32_FLOAT: 6,
    PIXEL_FORMAT_R32G32B32_UINT: 7,
    PIXEL_FORMAT_R32G32B32_SINT: 8,
    PIXEL_FORMAT_R16G16B16A16_TYPELESS: 9,
    PIXEL_FORMAT_R16G16B16A16_FLOAT: 10,
    PIXEL_FORMAT_R16G16B16A16_UNORM: 11,
    PIXEL_FORMAT_R16G16B16A16_UINT: 12,
    PIXEL_FORMAT_R16G16B16A16_SNORM: 13,
    PIXEL_FORMAT_R16G16B16A16_SINT: 14,
    PIXEL_FORMAT_R32G32_TYPELESS: 15,
    PIXEL_FORMAT_R32G32_FLOAT: 16,
    PIXEL_FORMAT_R32G32_UINT: 17,
    PIXEL_FORMAT_R32G32_SINT: 18,
    PIXEL_FORMAT_R32G8X24_TYPELESS: 19,
    PIXEL_FORMAT_D32_FLOAT_S8X24_UINT: 20,
    PIXEL_FORMAT_R32_FLOAT_X8X24_TYPELESS: 21,
    PIXEL_FORMAT_X32_TYPELESS_G8X24_UINT: 22,
    PIXEL_FORMAT_R10G10B10A2_TYPELESS: 23,
    PIXEL_FORMAT_R10G10B10A2_UNORM: 24,
    PIXEL_FORMAT_R10G10B10A2_UINT: 25,
    PIXEL_FORMAT_R11G11B10_FLOAT: 26,
    PIXEL_FORMAT_R8G8B8A8_TYPELESS: 27,
    PIXEL_FORMAT_R8G8B8A8_UNORM: 28,
    PIXEL_FORMAT_R8G8B8A8_UNORM_SRGB: 29,
    PIXEL_FORMAT_R8G8B8A8_UINT: 30,
    PIXEL_FORMAT_R8G8B8A8_SNORM: 31,
    PIXEL_FORMAT_R8G8B8A8_SINT: 32,
    PIXEL_FORMAT_R16G16_TYPELESS: 33,
    PIXEL_FORMAT_R16G16_FLOAT: 34,
    PIXEL_FORMAT_R16G16_UNORM: 35,
    PIXEL_FORMAT_R16G16_UINT: 36,
    PIXEL_FORMAT_R16G16_SNORM: 37,
    PIXEL_FORMAT_R16G16_SINT: 38,
    PIXEL_FORMAT_R32_TYPELESS: 39,
    PIXEL_FORMAT_D32_FLOAT: 40,
    PIXEL_FORMAT_R32_FLOAT: 41,
    PIXEL_FORMAT_R32_UINT: 42,
    PIXEL_FORMAT_R32_SINT: 43,
    PIXEL_FORMAT_R24G8_TYPELESS: 44,
    PIXEL_FORMAT_D24_UNORM_S8_UINT: 45,
    PIXEL_FORMAT_R24_UNORM_X8_TYPELESS: 46,
    PIXEL_FORMAT_X24_TYPELESS_G8_UINT: 47,
    PIXEL_FORMAT_R8G8_TYPELESS: 48,
    PIXEL_FORMAT_R8G8_UNORM: 49,
    PIXEL_FORMAT_R8G8_UINT: 50,
    PIXEL_FORMAT_R8G8_SNORM: 51,
    PIXEL_FORMAT_R8G8_SINT: 52,
    PIXEL_FORMAT_R16_TYPELESS: 53,
    PIXEL_FORMAT_R16_FLOAT: 54,
    PIXEL_FORMAT_D16_UNORM: 55,
    PIXEL_FORMAT_R16_UNORM: 56,
    PIXEL_FORMAT_R16_UINT: 57,
    PIXEL_FORMAT_R16_SNORM: 58,
    PIXEL_FORMAT_R16_SINT: 59,
    PIXEL_FORMAT_R8_TYPELESS: 60,
    PIXEL_FORMAT_R8_UNORM: 61,
    PIXEL_FORMAT_R8_UINT: 62,
    PIXEL_FORMAT_R8_SNORM: 63,
    PIXEL_FORMAT_R8_SINT: 64,
    PIXEL_FORMAT_A8_UNORM: 65,
    PIXEL_FORMAT_R1_UNORM: 66,
    PIXEL_FORMAT_R9G9B9E5_SHAREDEXP: 67,
    PIXEL_FORMAT_R8G8_B8G8_UNORM: 68,
    PIXEL_FORMAT_G8R8_G8B8_UNORM: 69,
    PIXEL_FORMAT_BC1_TYPELESS: 70,
    PIXEL_FORMAT_BC1_UNORM: 71,
    PIXEL_FORMAT_BC1_UNORM_SRGB: 72,
    PIXEL_FORMAT_BC2_TYPELESS: 73,
    PIXEL_FORMAT_BC2_UNORM: 74,
    PIXEL_FORMAT_BC2_UNORM_SRGB: 75,
    PIXEL_FORMAT_BC3_TYPELESS: 76,
    PIXEL_FORMAT_BC3_UNORM: 77,
    PIXEL_FORMAT_BC3_UNORM_SRGB: 78,
    PIXEL_FORMAT_BC4_TYPELESS: 79,
    PIXEL_FORMAT_BC4_UNORM: 80,
    PIXEL_FORMAT_BC4_SNORM: 81,
    PIXEL_FORMAT_BC5_TYPELESS: 82,
    PIXEL_FORMAT_BC5_UNORM: 83,
    PIXEL_FORMAT_BC5_SNORM: 84,
    PIXEL_FORMAT_B5G6R5_UNORM: 85,
    PIXEL_FORMAT_B5G5R5A1_UNORM: 86,
    PIXEL_FORMAT_B8G8R8A8_UNORM: 87,
    PIXEL_FORMAT_B8G8R8X8_UNORM: 88,
    PIXEL_FORMAT_R10G10B10_XR_BIAS_A2_UNORM: 89,
    PIXEL_FORMAT_B8G8R8A8_TYPELESS: 90,
    PIXEL_FORMAT_B8G8R8A8_UNORM_SRGB: 91,
    PIXEL_FORMAT_B8G8R8X8_TYPELESS: 92,
    PIXEL_FORMAT_B8G8R8X8_UNORM_SRGB: 93,
    PIXEL_FORMAT_BC6H_TYPELESS: 94,
    PIXEL_FORMAT_BC6H_UF16: 95,
    PIXEL_FORMAT_BC6H_SF16: 96,
    PIXEL_FORMAT_BC7_TYPELESS: 97,
    PIXEL_FORMAT_BC7_UNORM: 98,
    PIXEL_FORMAT_BC7_UNORM_SRGB: 99,
    PIXEL_FORMAT_SENTINEL: 100,
    PIXEL_FORMAT_FORCE_UINT: 4294967295
});

export const DepthStencilFormat = Object.freeze({
    DSFMT_UNKNOWN: 0,
    DSFMT_D24S8: 1,
    DSFMT_D24X8: 2,
    DSFMT_D24FS8: 3,
    DSFMT_D32F: 4,
    DSFMT_D32: 5,
    DSFMT_READABLE: 6,
    DSFMT_AUTO: 7,
    DSFMT_D16_LOCKABLE: 8,
    DSFMT_D15S1: 9,
    DSFMT_D24X4S4: 10,
    DSFMT_D16: 11,
    DSFMT_D32F_LOCKABLE: 12
});

/** Carbon texture/buffer view type (Tr2RenderContextEnum::TextureType). */
export const TextureType = Object.freeze({
    TEX_TYPE_1D: 1,
    TEX_TYPE_2D: 2,
    TEX_TYPE_3D: 3,
    TEX_TYPE_CUBE: 4,
    TEX_TYPE_TYPELESS: 5,
    TEX_TYPE_BUFFER: 6,
    TEX_TYPE_STRUCTURED_BUFFER: 7,
    TEX_TYPE_TBUFFER: 8,
    TEX_TYPE_BYTEADDRESS_BUFFER: 9,
    TEX_TYPE_UAV_RWTYPED: 10,
    TEX_TYPE_UAV_RWSTRUCTURED: 11,
    TEX_TYPE_UAV_RWBYTEADDRESS: 12,
    TEX_TYPE_UAV_APPEND_STRUCTURED: 13,
    TEX_TYPE_UAV_CONSUME_STRUCTURED: 14,
    TEX_TYPE_UAV_RWSTRUCTURED_WITH_COUNTER: 15,
    TEX_TYPE_RAYTRACING_ACCELERATION_STRUCTURE: 16,
    TEX_TYPE_INVALID: 17
});


// Carbon keeps the three functions below in the same header as the enum they
// switch over (`imageio/include/PixelFormat.h:119-295`), so they live here too.
// They are tables, not policy: every value is transcribed, including the ones
// that look wrong.

const COMPRESSED_FORMATS = new Set([
    PixelFormat.PIXEL_FORMAT_BC1_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC1_UNORM,
    PixelFormat.PIXEL_FORMAT_BC1_UNORM_SRGB,
    PixelFormat.PIXEL_FORMAT_BC2_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC2_UNORM,
    PixelFormat.PIXEL_FORMAT_BC2_UNORM_SRGB,
    PixelFormat.PIXEL_FORMAT_BC3_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC3_UNORM,
    PixelFormat.PIXEL_FORMAT_BC3_UNORM_SRGB,
    PixelFormat.PIXEL_FORMAT_BC4_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC4_UNORM,
    PixelFormat.PIXEL_FORMAT_BC4_SNORM,
    PixelFormat.PIXEL_FORMAT_BC5_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC5_UNORM,
    PixelFormat.PIXEL_FORMAT_BC5_SNORM,
    PixelFormat.PIXEL_FORMAT_BC6H_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC6H_UF16,
    PixelFormat.PIXEL_FORMAT_BC6H_SF16,
    PixelFormat.PIXEL_FORMAT_BC7_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC7_UNORM,
    PixelFormat.PIXEL_FORMAT_BC7_UNORM_SRGB
]);

/** Eight-byte block formats; every other compressed format is sixteen. */
const EIGHT_BYTE_BLOCK_FORMATS = new Set([
    PixelFormat.PIXEL_FORMAT_BC1_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC1_UNORM,
    PixelFormat.PIXEL_FORMAT_BC1_UNORM_SRGB,
    PixelFormat.PIXEL_FORMAT_BC4_TYPELESS,
    PixelFormat.PIXEL_FORMAT_BC4_UNORM,
    PixelFormat.PIXEL_FORMAT_BC4_SNORM
]);

/**
 * Whether a format stores blocks rather than pixels.
 *
 * @param {number} format A `PixelFormat` value.
 * @returns {boolean} True for the BC family.
 */
export function IsCompressedFormat(format)
{
    return COMPRESSED_FORMATS.has(format);
}

/**
 * Bytes in one compressed block, or 0 when the format is not a block image.
 *
 * @param {number} format A `PixelFormat` value.
 * @returns {number} Block size in bytes.
 */
export function GetBlockByteSize(format)
{
    if (!COMPRESSED_FORMATS.has(format)) return 0;

    return EIGHT_BYTE_BLOCK_FORMATS.has(format) ? 8 : 16;
}

// CARBON'S TABLE, INCLUDING THE THREE-CHANNEL ENTRY. The R32G32B32 formats are
// listed with the four-channel ones and so report 16 bytes rather than 12
// (`PixelFormat.h:203-215`). That is deliberate transcription, not an oversight:
// changing it here would make our mip pitch disagree with the engine we mirror.
const BYTES_PER_PIXEL = new Map([
    [ 16, [
        PixelFormat.PIXEL_FORMAT_R32G32B32A32_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R32G32B32A32_FLOAT,
        PixelFormat.PIXEL_FORMAT_R32G32B32A32_UINT,
        PixelFormat.PIXEL_FORMAT_R32G32B32A32_SINT,
        PixelFormat.PIXEL_FORMAT_R32G32B32_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R32G32B32_FLOAT,
        PixelFormat.PIXEL_FORMAT_R32G32B32_UINT,
        PixelFormat.PIXEL_FORMAT_R32G32B32_SINT
    ] ],
    [ 8, [
        PixelFormat.PIXEL_FORMAT_R16G16B16A16_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R16G16B16A16_FLOAT,
        PixelFormat.PIXEL_FORMAT_R16G16B16A16_UNORM,
        PixelFormat.PIXEL_FORMAT_R16G16B16A16_UINT,
        PixelFormat.PIXEL_FORMAT_R16G16B16A16_SNORM,
        PixelFormat.PIXEL_FORMAT_R16G16B16A16_SINT,
        PixelFormat.PIXEL_FORMAT_R32G32_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R32G32_FLOAT,
        PixelFormat.PIXEL_FORMAT_R32G32_UINT,
        PixelFormat.PIXEL_FORMAT_R32G32_SINT,
        PixelFormat.PIXEL_FORMAT_R32G8X24_TYPELESS,
        PixelFormat.PIXEL_FORMAT_D32_FLOAT_S8X24_UINT,
        PixelFormat.PIXEL_FORMAT_R32_FLOAT_X8X24_TYPELESS,
        PixelFormat.PIXEL_FORMAT_X32_TYPELESS_G8X24_UINT
    ] ],
    [ 4, [
        PixelFormat.PIXEL_FORMAT_R10G10B10A2_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R10G10B10A2_UNORM,
        PixelFormat.PIXEL_FORMAT_R10G10B10A2_UINT,
        PixelFormat.PIXEL_FORMAT_R11G11B10_FLOAT,
        PixelFormat.PIXEL_FORMAT_R8G8B8A8_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R8G8B8A8_UNORM,
        PixelFormat.PIXEL_FORMAT_R8G8B8A8_UNORM_SRGB,
        PixelFormat.PIXEL_FORMAT_R8G8B8A8_UINT,
        PixelFormat.PIXEL_FORMAT_R8G8B8A8_SNORM,
        PixelFormat.PIXEL_FORMAT_R8G8B8A8_SINT,
        PixelFormat.PIXEL_FORMAT_R16G16_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R16G16_FLOAT,
        PixelFormat.PIXEL_FORMAT_R16G16_UNORM,
        PixelFormat.PIXEL_FORMAT_R16G16_UINT,
        PixelFormat.PIXEL_FORMAT_R16G16_SNORM,
        PixelFormat.PIXEL_FORMAT_R16G16_SINT,
        PixelFormat.PIXEL_FORMAT_R32_TYPELESS,
        PixelFormat.PIXEL_FORMAT_D32_FLOAT,
        PixelFormat.PIXEL_FORMAT_R32_FLOAT,
        PixelFormat.PIXEL_FORMAT_R32_UINT,
        PixelFormat.PIXEL_FORMAT_R32_SINT,
        PixelFormat.PIXEL_FORMAT_R24G8_TYPELESS,
        PixelFormat.PIXEL_FORMAT_D24_UNORM_S8_UINT,
        PixelFormat.PIXEL_FORMAT_R24_UNORM_X8_TYPELESS,
        PixelFormat.PIXEL_FORMAT_X24_TYPELESS_G8_UINT,
        PixelFormat.PIXEL_FORMAT_R9G9B9E5_SHAREDEXP,
        PixelFormat.PIXEL_FORMAT_R8G8_B8G8_UNORM,
        PixelFormat.PIXEL_FORMAT_G8R8_G8B8_UNORM,
        PixelFormat.PIXEL_FORMAT_B8G8R8A8_UNORM,
        PixelFormat.PIXEL_FORMAT_B8G8R8X8_UNORM,
        PixelFormat.PIXEL_FORMAT_R10G10B10_XR_BIAS_A2_UNORM,
        PixelFormat.PIXEL_FORMAT_B8G8R8A8_TYPELESS,
        PixelFormat.PIXEL_FORMAT_B8G8R8A8_UNORM_SRGB,
        PixelFormat.PIXEL_FORMAT_B8G8R8X8_TYPELESS,
        PixelFormat.PIXEL_FORMAT_B8G8R8X8_UNORM_SRGB
    ] ],
    [ 2, [
        PixelFormat.PIXEL_FORMAT_R8G8_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R8G8_UNORM,
        PixelFormat.PIXEL_FORMAT_R8G8_UINT,
        PixelFormat.PIXEL_FORMAT_R8G8_SNORM,
        PixelFormat.PIXEL_FORMAT_R8G8_SINT,
        PixelFormat.PIXEL_FORMAT_R16_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R16_FLOAT,
        PixelFormat.PIXEL_FORMAT_D16_UNORM,
        PixelFormat.PIXEL_FORMAT_R16_UNORM,
        PixelFormat.PIXEL_FORMAT_R16_UINT,
        PixelFormat.PIXEL_FORMAT_R16_SNORM,
        PixelFormat.PIXEL_FORMAT_R16_SINT,
        PixelFormat.PIXEL_FORMAT_B5G6R5_UNORM,
        PixelFormat.PIXEL_FORMAT_B5G5R5A1_UNORM
    ] ],
    [ 1, [
        PixelFormat.PIXEL_FORMAT_R8_TYPELESS,
        PixelFormat.PIXEL_FORMAT_R8_UNORM,
        PixelFormat.PIXEL_FORMAT_R8_UINT,
        PixelFormat.PIXEL_FORMAT_R8_SNORM,
        PixelFormat.PIXEL_FORMAT_R8_SINT,
        PixelFormat.PIXEL_FORMAT_A8_UNORM
    ] ]
]);

const BYTES_BY_FORMAT = new Map();

for (const [ bytes, formats ] of BYTES_PER_PIXEL)
{
    for (const format of formats) BYTES_BY_FORMAT.set(format, bytes);
}

/**
 * Bytes in one pixel, or 0 for a compressed or unknown format.
 *
 * @param {number} format A `PixelFormat` value.
 * @returns {number} Size in bytes.
 */
export function GetBytesPerPixel(format)
{
    const bytes = BYTES_BY_FORMAT.get(format);

    return bytes === undefined ? 0 : bytes;
}
