// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Interior/Tr2InteriorRenderBatch.h
// Generated by format-carbon carbon-class --emit. Verify against interior/Tr2IntKeyGenerator.json.
import { carbon, impl, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2IntKeyGenerator (interior) - generated from schema shapeHash 22c2dcb4.... */
@type.define({ className: "Tr2IntKeyGenerator", family: "interior" })
export class Tr2IntKeyGenerator extends CjsModel
{

  /** Carbon static comparator for interior render batches. */
  @carbon.method
  @impl.implemented
  static Less(batch1, batch2)
  {
    if (batch1.renderingMode < batch2.renderingMode) return true;
    if (batch1.renderingMode > batch2.renderingMode) return false;
    return batch1.renderingMode === 4 ? batch1.depth < batch2.depth : false;
  }

  /** Carbon requests stable sorting so authored decal order is preserved. */
  @carbon.method
  @impl.implemented
  static GetSortType()
  {
    return 2;
  }

  static ALLOW_GDPR = false;

}
