// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Interior/Tr2InteriorConstantBufferFormats.h
// Generated by format-carbon carbon-class --emit. Verify against interior/Tr2InteriorPerObjectPSData.json.
import { impl, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { mat4 } from "@carbonenginejs/core-math/mat4";
import { vec4 } from "@carbonenginejs/core-math/vec4";
import { Tr2InteriorPerObjectLightData } from "./Tr2InteriorPerObjectLightData.js";

/** Tr2InteriorPerObjectPSData (interior) - generated from schema shapeHash 774698be.... */
@type.define({ className: "Tr2InteriorPerObjectPSData", family: "interior" })
export class Tr2InteriorPerObjectPSData extends CjsModel
{

  /** lightCount (int32_t) */
  @type.int32
  lightCount = 0;

  /** padding (int32_t[3]) */
  @type.array("int32")
  padding = [ 0, 0, 0 ];

  /** pointLights (Tr2InteriorPerObjectLightData[10]) */
  @type.array({
    kind: "struct",
    className: "Tr2InteriorPerObjectLightData"
  })
  pointLights = Array.from({ length: 10 }, () => new Tr2InteriorPerObjectLightData());

  /** shadowCaster0 (Vector4) */
  @type.vec4
  shadowCaster0 = vec4.create();

  /** shadowCaster1 (Vector4) */
  @type.vec4
  shadowCaster1 = vec4.create();

  /** spotLights (Matrix[4]) */
  @type.array("mat4")
  spotLights = Array.from({ length: 4 }, () => mat4.create());

  @impl.custom
  @impl.reason("Preserves Carbon fixed-array cardinalities when importing plain JS values.")
  SetValues(values = {}, options = {})
  {
    const normalized = { ...values };
    if (Object.hasOwn(values, "padding"))
    {
      normalized.padding = Array.from({ length: 3 }, (_, index) => Number(values.padding?.[index] ?? 0) | 0);
    }
    if (Object.hasOwn(values, "pointLights"))
    {
      normalized.pointLights = Array.from({ length: 10 }, (_, index) =>
        values.pointLights?.[index] ?? new Tr2InteriorPerObjectLightData());
    }
    if (Object.hasOwn(values, "spotLights"))
    {
      normalized.spotLights = FixedMat4Array(values.spotLights, 4);
    }
    return super.SetValues(normalized, options);
  }

}

function FixedMat4Array(values, count)
{
  return Array.from({ length: count }, (_, index) =>
  {
    const value = values?.[index];
    return value?.length === 16 ? mat4.copy(mat4.create(), value) : mat4.create();
  });
}
