// Shared provenance guard for runtime-audio's Carbon class generator.
// Kept separate so the release test suite can exercise the destructive-write
// boundary without executing a schema generation run.
export const GENERATED_CLASS_BANNER = "// Generated by format-carbon carbon-class --emit.";

/** Returns whether a source file is owned by the Carbon class generator. */
export function isGeneratedClassSource(source)
{
  return String(source).includes(GENERATED_CLASS_BANNER);
}

/** Refuses to overwrite an existing maintained source file. */
export function assertGeneratedTargetWritable(file, existingSource)
{
  if (!isGeneratedClassSource(existingSource))
  {
    throw new Error(`Refusing to overwrite maintained source: ${file}`);
  }
}
