import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { spawnSync } from "node:child_process";
import { readGeneratedOwnership, createOwnershipSummary, updateOwnershipSummary, assertGeneratedInstallAllowed } from "../../scripts/trinity/generated-ownership.js";

/** Creates a synthetic source/schema corpus, with cleanup confined to its temp directory. */
async function fixture(t, sources, schemas)
{
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "cjs-ownership-test-"));
  t.after(async () =>
  {
    assert.equal(path.dirname(root), path.resolve(os.tmpdir()));
    assert.ok(path.basename(root).startsWith("cjs-ownership-test-"));
    await fs.rm(root, { recursive: true, force: true });
  });
  for (const [name, source] of Object.entries(sources))
  {
    const file = path.join(root, "src", name);
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, source);
  }
  for (const [key, doc] of Object.entries(schemas))
  {
    const file = path.join(root, "schema", `${key}.json`);
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, JSON.stringify(doc));
  }
  return { sourceRoot: path.join(root, "src"), schemaRoot: path.join(root, "schema") };
}

test("installation protects maintained, external-layer and dropped identities even at a new output path", async t =>
{
  const options = await fixture(t, {
    "trinity/sprite2d/Texture.js": '@meta.define({className:"Texture",family:"sprite2d"}) export class Texture {}',
    "resource/Other.js": 'export class Other {}',
    "trinity/dropped/Old.js": 'export class Old {}',
    "trinity/generated/sprite2d/Fresh.js": 'export class Fresh {}'
  }, Object.fromEntries(["Texture", "Other", "Old", "Fresh"].map(blueClass => [`sprite2d/${blueClass}`, {blueClass, family:"sprite2d", methods:[]}])));
  const inventory = await readGeneratedOwnership(options);
  for (const name of ["Texture", "Other", "Old"])
    assert.throws(() => assertGeneratedInstallAllowed(inventory, name, "sprite2d"), /source exists/);
  assert.doesNotThrow(() => assertGeneratedInstallAllowed(inventory, "Fresh", "sprite2d"));
  assert.equal(createOwnershipSummary(inventory).classes.written, 1);
});

test("duplicate class identities fail instead of preferring maintained source", async t =>
{
  const options = await fixture(t, {
    "trinity/core/A.js": 'export class A {}',
    "trinity/generated/core/A.js": 'export class A {}'
  }, {"core/A": {blueClass:"A", family:"core"}});
  await assert.rejects(readGeneratedOwnership(options), /Duplicate Carbon identity A/);
});

test("canonical metadata identity overrides the JavaScript name and generation banners", async t =>
{
  const options = await fixture(t, {
    "trinity/core/A.js": '// Generated by format-carbon carbon-class --emit.\n@meta.define({className:"NativeA",family:"core"}) export class LocalA {}',
    "resource/B.js": 'export class LocalB {}\nCjsSchema.define(LocalB, {className:"NativeB"});'
  }, {"core/NativeA": {blueClass:"NativeA", family:"core"}, "core/NativeB": {blueClass:"NativeB", family:"core"}});
  const inventory = await readGeneratedOwnership(options);
  assert.equal(inventory.records.get("NativeA").state, "maintained");
  assert.throws(() => assertGeneratedInstallAllowed(inventory, "NativeB", "core"), /resource\/B.js/);
});

test("promotion refresh is deterministic and preserves historical reservations without using stale live skips", async t =>
{
  const options = await fixture(t, {
    "trinity/generated/raytracing/Mesh.js": '@meta.define({className:"Mesh",family:"raytracing"}) export class Mesh {}'
  }, {"raytracing/Mesh": {blueClass:"Mesh", family:"raytracing"}});
  const generation = {skipped:[{className:"Reserved",family:"wod",schema:"wod/Reserved.json",reason:"owned by runtime-resource"}]};
  const previous = {generation, classes:{written:999,skipped:999}, skipped:[{className:"Stale",family:"core",reason:"hand-maintained source exists"}]};
  const before = updateOwnershipSummary(previous, await readGeneratedOwnership(options));
  assert.deepEqual(before.classes, {written:1,skipped:0});
  await fs.mkdir(path.join(options.sourceRoot,"trinity/raytracing"));
  await fs.rename(path.join(options.sourceRoot,"trinity/generated/raytracing/Mesh.js"), path.join(options.sourceRoot,"trinity/raytracing/Mesh.js"));
  const inventory = await readGeneratedOwnership(options);
  const after = updateOwnershipSummary(before, inventory);
  assert.deepEqual(after.classes, {written:0,skipped:1});
  assert.equal(after.skipped[0].reason,"hand-maintained source exists");
  assert.deepEqual(after.paritySubjects.map(entry => entry.className).sort(), ["Mesh", "Stale"]);
  assert.deepEqual(after.generation,generation);
  assert.equal(JSON.stringify(after),JSON.stringify(updateOwnershipSummary(after,await readGeneratedOwnership(options))));
});

test("schema-specific exclusions still protect absent classes and enum-owned identities", () =>
{
  const inventory = {records:new Map(),schemas:new Map([['WodPlaceableRes',[{family:"wod"}]],['GrannyDeprecationLevel',[{family:"resources"}]],['TriColor',[{family:"include"},{family:"trinityCore"}] ]])};
  const reservations = [
    {family:"wod",className:"WodPlaceableRes",reason:"owned by runtime-resource"},
    {family:"resources",className:"GrannyDeprecationLevel",reason:"owned by runtime-resource"},
    {family:"include",className:"TriColor",reason:"canonical runtime family is trinityCore"}
  ];
  for (const entry of reservations)
    assert.throws(() => assertGeneratedInstallAllowed(inventory,entry.className,entry.family,reservations),/Cannot install/);
  assert.doesNotThrow(() => assertGeneratedInstallAllowed(inventory,"TriColor","trinityCore",reservations));
});

test("a generated enum cannot be overwritten by a newly emitted class", async t =>
{
  const options = await fixture(t, {
    "resource/generated/resources/Mode.js": 'export const Mode = Object.freeze({A:1});'
  }, {"resources/Mode":{blueClass:"Mode",family:"resources"}});
  const inventory = await readGeneratedOwnership(options);
  assert.throws(() => assertGeneratedInstallAllowed(inventory,"Mode","resources"), /source exists/);
});

test("public parity keeps previously clean subjects and adds newly promoted obligations", async t =>
{
  const options = await fixture(t, {
    "trinity/core/A.js": 'export class A { Tick() {} }',
    "trinity/generated/core/B.js": 'export class B {}'
  }, Object.fromEntries(["A", "B"].map(blueClass => [`core/${blueClass}`, {blueClass,family:"core",nativeMethods:[{cppName:"Tick"}]}])));
  const root = path.dirname(options.sourceRoot);
  for (const directory of ["scripts/trinity", "src/trinity/dropped", "src/global/blue", "src/trinityal"])
    await fs.mkdir(path.join(root,directory),{recursive:true});
  await fs.writeFile(path.join(root,"package.json"),'{"type":"module"}');
  await fs.writeFile(path.join(root,"scripts/trinity-parity-baseline.json"),'{"findings":[]}');
  const auditUrl = new URL("../../scripts/trinity/audit_public_method_parity.js",import.meta.url);
  let script = await fs.readFile(auditUrl,"utf8");
  script = script.replace('from "@babel/parser"',`from ${JSON.stringify(import.meta.resolve("@babel/parser"))}`);
  script = script.replace('from "./carbon-decorators.js"',`from ${JSON.stringify(new URL("carbon-decorators.js",auditUrl).href)}`);
  const audit = path.join(root,"scripts/trinity/audit_public_method_parity.js");
  await fs.writeFile(audit,script);
  const initial = {skipped:[{className:"A",family:"core",reason:"hand-maintained source exists"}]};
  const summary = updateOwnershipSummary(initial,await readGeneratedOwnership(options));
  const summaryFile = path.join(root,"src/trinity/generated/summary.json");
  await fs.writeFile(summaryFile,JSON.stringify(summary));
  const run = () => spawnSync(process.execPath,[audit,"--schema-root",options.schemaRoot],{encoding:"utf8",windowsHide:true});
  assert.equal(run().status,0,"a previously clean class remains a subject without needing a baseline finding");
  await fs.writeFile(path.join(options.sourceRoot,"trinity/core/A.js"),'export class A {}');
  const broken = run();
  assert.equal(broken.status,1);
  assert.match(broken.stderr,/omitted A.Tick/);
  await fs.writeFile(path.join(options.sourceRoot,"trinity/core/A.js"),'export class A { Tick() {} }');
  await fs.rename(path.join(options.sourceRoot,"trinity/generated/core/B.js"),path.join(options.sourceRoot,"trinity/core/B.js"));
  await fs.writeFile(summaryFile,JSON.stringify(updateOwnershipSummary(summary,await readGeneratedOwnership(options))));
  const promoted = run();
  assert.equal(promoted.status,1);
  assert.match(promoted.stderr,/omitted B.Tick/);
});
