import assert from 'node:assert/strict';
import test from 'node:test';
import {existsSync,readFileSync} from 'node:fs';
import {INotify,NotifyModified} from '../../npm/dist/global/blue/index.js';
import {CjsSchema} from '../../npm/dist/global/schema/index.js';
import {Tr2Sprite2dTexture} from '../../npm/dist/trinity/index.js';

test('sprite texture edits notify native targets once after coalesced changed values',()=>{
  const texture=new Tr2Sprite2dTexture(),seen=[];
  assert.equal(CjsSchema.cast(texture,INotify),texture);
  texture.RegisterForChangeNotification({Sprite2dTextureChanged(changed){
    seen.push({changed,rotation:changed.rotation,translation:Array.from(changed.translation),useTransform:changed.useTransform});
  }});
  CjsSchema.setValues(texture,{rotation:0.75,translation:[2,3],useTransform:true});
  assert.deepEqual(seen,[{changed:texture,rotation:0.75,translation:[2,3],useTransform:true}]);
  CjsSchema.setValues(texture,{rotation:0.75,translation:[2,3],useTransform:true});
  assert.equal(seen.length,1,'equal values do not send a second notification');
  CjsSchema.setValues(texture,{name:'renamed'});assert.equal(seen.length,1,'name is not native NOTIFY');
});

test('duplicate registration and unregister follow native identity-set semantics',()=>{
  const texture=new Tr2Sprite2dTexture(),seen=[];
  const first={Sprite2dTextureChanged:changed=>seen.push(['first',changed])};
  const second={Sprite2dTextureChanged:changed=>seen.push(['second',changed])};
  texture.RegisterForChangeNotification(first);texture.RegisterForChangeNotification(first);texture.RegisterForChangeNotification(second);
  assert.equal(texture.OnModified('rotation'),true);
  assert.equal(seen.length,2);assert.ok(seen.every(entry=>entry[1]===texture));
  texture.UnregisterForChangeNotification(first);texture.UnregisterForChangeNotification(first);seen.length=0;
  texture.SetDirty();assert.deepEqual(seen,[['second',texture]]);
  texture.UnregisterForChangeNotification(second);texture.SetDirty();assert.equal(seen.length,1);
});

test('atlas callbacks and explicit changed-name arrays use the same listener path',()=>{
  const texture=new Tr2Sprite2dTexture(),seen=[];
  texture.RegisterForChangeNotification({Sprite2dTextureChanged:changed=>seen.push(changed)});
  texture.AtlasTextureChanged({});NotifyModified(texture,['rotation','scalingCenter']);
  assert.deepEqual(seen,[texture,texture]);
  texture.OnModified(null);assert.deepEqual(seen,[texture,texture,texture]);
});

test('sprite texture notification requires the native callback contract',()=>{
  const texture=new Tr2Sprite2dTexture();texture.RegisterForChangeNotification({});
  assert.throws(()=>texture.OnModified('rotation'),/Sprite2dTextureChanged/);
});

test('sprite texture promotion preserves one registered identity and generated ownership protection',()=>{
  assert.equal(CjsSchema.GetConstructor('Tr2Sprite2dTexture'),Tr2Sprite2dTexture);
  assert.equal(existsSync(new URL('../../src/trinity/generated/sprite2d/Tr2Sprite2dTexture.js',import.meta.url)),false);
  const source=readFileSync(new URL('../../src/trinity/sprite2d/Tr2Sprite2dTexture.js',import.meta.url),'utf8');
  assert.ok(!source.includes('Generated by format-carbon'));
  const summary=JSON.parse(readFileSync(new URL('../../src/trinity/generated/summary.json',import.meta.url),'utf8'));
  assert.ok(summary.skipped.some(entry=>entry.className==='Tr2Sprite2dTexture'&&entry.reason==='hand-maintained source exists'));
});

function atlas(width=128,height=64) {
  const listeners=new Set();
  return {listeners,GetWidth:()=>width,GetHeight:()=>height,IsGood:()=>true,IsLoading:()=>false,
    RegisterForChangeNotification:target=>listeners.add(target),UnregisterForChangeNotification:target=>listeners.delete(target)};
}

test('sprite atlas replacement, cropping and Apply preserve the native callback order',()=>{
  const texture=new Tr2Sprite2dTexture(),first=atlas(),second=atlas(256,128),calls=[];
  assert.equal(texture.GetWidth(),0);assert.equal(texture.IsGood(),false);assert.equal(texture.IsLoading(),false);
  texture.SetAtlasTexture(first);assert.ok(first.listeners.has(texture));assert.equal(texture.GetAtlasTexture(),first);
  assert.equal(texture.GetHeight(),64);assert.equal(texture.IsGood(),true);
  const renderer={SetTexture:(...args)=>calls.push(['texture',...args]),SetTextureWindow:(...args)=>calls.push(['window',...args]),
    SetTextureTransform:(...args)=>calls.push(['transform',...args]),SetTileMode:(...args)=>calls.push(['tile',...args])};
  texture.Apply(renderer,2);assert.deepEqual(calls.map(c=>c[0]),['texture','transform','tile']);
  texture.srcWidth=128;texture.srcHeight=64;calls.length=0;texture.Apply(renderer,2);
  assert.deepEqual(calls.map(c=>c[0]),['texture','transform','tile'],'exact full rectangle needs no window');
  texture.srcX=3;calls.length=0;texture.Apply(renderer,2);assert.deepEqual(calls[1],['window',2,3,0,128,64]);
  assert.deepEqual(calls.map(c=>c[0]),['texture','window','transform','tile']);
  texture.SetAtlasTexture(second);assert.equal(first.listeners.size,0);assert.ok(second.listeners.has(texture));
  texture.Destroy();texture.Destroy();assert.equal(second.listeners.size,0);assert.equal(texture.GetAtlasTexture(),null);
});

test('repeat flags retain the native unshifted setter quirk while tiling preserves unrelated bits',()=>{
  const texture=new Tr2Sprite2dTexture();texture.tileX=true;texture.tileY=true;
  texture.repeatMode=1;assert.equal(texture.repeatMode,0,'native writes 1 as FORCEOPAQUE, not MIRROR');
  texture.repeatMode=2;assert.equal(texture.repeatMode,1);assert.equal(texture._settings,27);
  texture.tileX=false;assert.equal(texture.tileY,true);assert.equal(texture._settings,19);
  texture.repeatMode=4;assert.equal(texture.repeatMode,2);assert.equal(texture._settings,21);
});

test('centered texture matrices apply oriented nonuniform scaling before rotation and translation',()=>{
  const texture=new Tr2Sprite2dTexture();assert.equal(texture.GetTransform(),null);
  texture.useTransform=true;texture.scalingCenter.set([1,2]);texture.scale.set([2,3]);texture.scalingRotation=Math.PI/2;
  texture.rotationCenter.set([4,5]);texture.rotation=Math.PI/2;texture.translation.set([6,7]);
  const transform=texture.GetTransform(),expected=[0,3,0,0,-2,0,0,0,0,0,1,0,17,6,0,1];
  transform.forEach((value,index)=>assert.ok(Math.abs(value-expected[index])<1e-5,`${index}: ${value}`));
  assert.equal(texture.GetTransform(),transform,'native retained output identity');
  texture.translation[0]=8;assert.ok(Math.abs(texture.GetTransform()[12]-19)<1e-5);
  texture.useTransform=false;assert.equal(texture.GetTransform(),null);
});

test('texture initialization accepts a supplied atlas and unsupported acquisition fails explicitly',()=>{
  const texture=new Tr2Sprite2dTexture();texture.atlasTexture=atlas();assert.equal(texture.Initialize(),true);
  assert.equal(texture.resPath,'');assert.throws(()=>texture.SetResPath('res:/ui/texture.dds'),/unported atlas resource acquisition/);
  assert.equal(texture.GetWidth(),128,'unsupported acquisition does not install a plain texture substitute');texture.Destroy();
});
