import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const banner = "// Generated by format-carbon carbon-class --emit.";

function read(relativePath)
{
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

test("generated audio classes are isolated from maintained graph source", () =>
{
  for (const relativePath of [
    "src/audio/generated/audio/AudEventKey.js",
    "src/audio/generated/audio/AudSettings.js",
    "src/audio/generated/trinityAudioApi/Tr2AudGeometryData.js",
  ])
  {
    assert.ok(read(relativePath).includes(banner), `${relativePath} retains generator provenance`);
  }

  assert.doesNotMatch(read("src/audio/trinity/audio/AudActionLog.js"), /Generated by format-carbon/u);
  assert.doesNotMatch(read("src/audio/trinity/audio/AudObstructionOcclusion.js"), /Generated by format-carbon/u);
});
