// Source: trinity/trinity/Utilities/GeometryUtils.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/AreaBoundsInfo.json.
import { meta } from "#schema";

/** Retains the quarantined native Granny area-bounds record that readers replace with detached bounds and vertex-count data. */
@meta.define({ className: "AreaBoundsInfo", family: "utilities" })
export class AreaBoundsInfo
{

  /** bounds (BoundingBox) */
  @meta.type.rawStruct("BoundingBox")
  bounds = null;

  /** vertexCount (granny_int32) */
  @meta.type.unknown
  vertexCount = null;

}
