// Source: trinity/trinity/Utilities/GeometryUtils.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/BoundingBox.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** BoundingBox (utilities) - generated from schema shapeHash a1f4788e.... */
@type.define({ className: "BoundingBox", family: "utilities" })
export class BoundingBox extends CjsModel
{

  /** min (granny_real32) */
  @type.unknown
  min = null;

  /** max (granny_real32) */
  @type.unknown
  max = null;

}
