// Source: trinity/trinity/Utilities/GeometryUtils.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/BoundingBox.json.
import { meta } from "#schema";

/** Retains the quarantined native Granny minimum/maximum bounds record that readers replace with math or plain data. */
@meta.define({ className: "BoundingBox", family: "utilities" })
export class BoundingBox
{

  /** min (granny_real32) */
  @meta.type.unknown
  min = null;

  /** max (granny_real32) */
  @meta.type.unknown
  max = null;

}
