// Source: trinity/trinity/PostProcess/Tr2PostProcessRenderer.h
// Generated by format-carbon carbon-class --emit. Verify against postProcess/CASConstants.json.
import { meta } from "#schema";

/** Retains the quarantined native CAS sharpening constants that renderer code replaces with packed numeric lanes. */
@meta.define({ className: "CASConstants", family: "postProcess" })
export class CASConstants
{

  /** const0 (uintfloat4) */
  @meta.type.unknown
  const0 = null;

  /** const1 (uintfloat4) */
  @meta.type.unknown
  const1 = null;

}
