// Source: trinity/trinity/PostProcess/Tr2PostProcessRenderer.h
// Generated by format-carbon carbon-class --emit. Verify against postProcess/CASConstants.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the quarantined native CAS sharpening constants that renderer code replaces with packed numeric lanes. */
@type.define({ className: "CASConstants", family: "postProcess" })
export class CASConstants extends CjsModel
{

  /** const0 (uintfloat4) */
  @type.unknown
  const0 = null;

  /** const1 (uintfloat4) */
  @type.unknown
  const1 = null;

}
