// Source: trinity/trinity/Eve/UI/EveSpherePinIndexTree.h
// Generated by format-carbon carbon-class --emit. Verify against eve/ui/EveSpherePinIndexTree.json.
import { meta } from "#schema";

/** Retains the quarantined pointer-backed spherical geometry index whose realization belongs to resource or engine spatial indexing. */
@meta.define({ className: "EveSpherePinIndexTree", family: "eve/ui" })
export class EveSpherePinIndexTree
{

  /** Face (struct) */
  @meta.type.unknown
  Face = null;

  /** TreeNode (struct) */
  @meta.type.unknown
  TreeNode = null;

  /** m_granny (TriGrannyResPtr) */
  @meta.type.objectRef("TriGrannyRes")
  granny = null;

  /** m_tree (TreeNode*) */
  @meta.type.objectRef("TreeNode")
  tree = 0;

  /** m_faces (Face*) */
  @meta.type.objectRef("Face")
  faces = 0;

  /** m_initialized (int) */
  @meta.type.int32
  initialized = 0;

  /** m_markedFaces (std::vector<Face*>) */
  @meta.type.list("Face")
  markedFaces = [];

}
