// Source: trinity/trinity/Eve/Renderable/EveSceneStaticParticles.h
// Generated by format-carbon carbon-class --emit. Verify against eve/perObjectData/EveSceneStaticParticlesPerObjectData.json.
import { type } from "#schema";
import { CjsModel } from "#model";
import { mat4 } from "#math/mat4";

/** Represents the retired static-particle payload for current and previous world matrices now written through RawData. */
@type.define({ className: "EveSceneStaticParticlesPerObjectData", family: "eve/perObjectData" })
export class EveSceneStaticParticlesPerObjectData extends CjsModel
{

  /** m_data.world (Matrix) */
  @type.mat4
  data = mat4.create();

}
