// Source: trinity/trinity/Include/ITriQuaternion.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriQuaternion.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the retired Blue/Python quaternion interface superseded by runtime quat values and schema quaternion fields. */
@type.define({ className: "ITriQuaternion", family: "include" })
export class ITriQuaternion extends CjsModel
{

  /** const (Quaternion * in )) */
  @type.unknown
  const = 0;

}
