// Source: trinity/trinity/Include/ITriVector.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriVector.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the retired Blue/Python vector interface superseded by runtime vec3 values and schema vector fields. */
@type.define({ className: "ITriVector", family: "include" })
export class ITriVector extends CjsModel
{

  /** const (Vector3 * in )) */
  @type.unknown
  const = 0;

}
