// Source: trinity/trinity/Include/ITriEffectParameter.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriEffectTextureParameter.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the pure texture-parameter interface identity superseded by maintained concrete texture-parameter graph classes. */
@type.define({ className: "ITriEffectTextureParameter", family: "include" })
export class ITriEffectTextureParameter extends CjsModel
{

  /** UV_SET_MAX_COUNT (static const size_t) */
  @type.unknown
  UV_SET_MAX_COUNT = 8;

}
