// Source: trinity/trinity/Include/ITriColor.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriColor.json.
import { meta } from "#schema";

/** Retains the retired Blue/Python color interface superseded by runtime vec4 values and schema color fields. */
@meta.define({ className: "ITriColor", family: "include" })
export class ITriColor
{

  /** const (::Color * in )) */
  @meta.type.rawStruct("::Color in )")
  const = 0;

}
