// Source: trinity/trinity/Include/ITriMatrix.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriMatrix.json.
import { meta } from "#schema";

/** Retains the retired Blue/Python matrix interface superseded by runtime mat4 values and schema matrix fields. */
@meta.define({ className: "ITriMatrix", family: "include" })
export class ITriMatrix
{

  /** _11 (float) */
  @meta.type.float32
  _11 = 0;

  /** const (Matrix * in )) */
  @meta.type.unknown
  const = 0;

}
