// Source: trinity/trinity/Include/ITriDevice.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriDevice.json.
import { meta } from "#schema";

/** Retains the native device interface identity while maintained graph state and injected engines divide its former responsibilities. */
@meta.define({ className: "ITriDevice", family: "include" })
export class ITriDevice
{

  /** adapter (uint32_t) */
  @meta.type.uint32
  adapter = 0;

}
