// Source: trinity/trinity/Include/ITriVector.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriVector.json.
import { meta } from "#schema";

/** Retains the retired Blue/Python vector interface superseded by runtime vec3 values and schema vector fields. */
@meta.define({ className: "ITriVector", family: "include" })
export class ITriVector
{

  /** const (Vector3 * in )) */
  @meta.type.unknown
  const = 0;

}
