// Source: trinity/trinity/Include/ITriDevice.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriDevice.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** ITriDevice (include) - generated from schema shapeHash 3a872fd8.... */
@type.define({ className: "ITriDevice", family: "include" })
export class ITriDevice extends CjsModel
{

  /** adapter (uint32_t) */
  @type.uint32
  adapter = 0;

}
