// Source: trinity/trinity/Include/ITriVector.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriVector.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** ITriVector (include) - generated from schema shapeHash 0d9037bc.... */
@type.define({ className: "ITriVector", family: "include" })
export class ITriVector extends CjsModel
{

  /** const (Vector3 * in )) */
  @type.unknown
  const = 0;

}
