// Source: trinity/trinity/Include/ITriColor.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriColor.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the retired Blue/Python color interface superseded by runtime vec4 values and schema color fields. */
@type.define({ className: "ITriColor", family: "include" })
export class ITriColor extends CjsModel
{

  /** const (::Color * in )) */
  @type.rawStruct("::Color in )")
  const = 0;

}
