// Source: trinity/trinity/Include/ITriMatrix.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriMatrix.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the retired Blue/Python matrix interface superseded by runtime mat4 values and schema matrix fields. */
@type.define({ className: "ITriMatrix", family: "include" })
export class ITriMatrix extends CjsModel
{

  /** _11 (float) */
  @type.float32
  _11 = 0;

  /** const (Matrix * in )) */
  @type.unknown
  const = 0;

}
