// Source: trinity/trinity/Include/ITriQuaternion.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriQuaternion.json.
import { meta } from "#schema";

/** Retains the retired Blue/Python quaternion interface superseded by runtime quat values and schema quaternion fields. */
@meta.define({ className: "ITriQuaternion", family: "include" })
export class ITriQuaternion
{

  /** const (Quaternion * in )) */
  @meta.type.unknown
  const = 0;

}
