// Source: trinity/trinity/Utilities/GeometryUtils.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/MeshBoundsInfo.json.
import { meta } from "#schema";

/** Retains the quarantined pointer-and-count Granny mesh-bounds record that readers replace with detached array-backed data. */
@meta.define({ className: "MeshBoundsInfo", family: "utilities" })
export class MeshBoundsInfo
{

  /** typeName (const char*) */
  @meta.type.objectRef("char")
  typeName = null;

  /** bounds (BoundingBox) */
  @meta.type.rawStruct("BoundingBox")
  bounds = null;

  /** areaCount (granny_int32) */
  @meta.type.unknown
  areaCount = null;

  /** areaInfos (AreaBoundsInfo*) */
  @meta.type.objectRef("AreaBoundsInfo")
  areaInfos = null;

  /** sourceMeshIndex (granny_int32) */
  @meta.type.unknown
  sourceMeshIndex = null;

  /** maxScreenSize (granny_int32) */
  @meta.type.unknown
  maxScreenSize = null;

  /** uvDensityCount (granny_int32) */
  @meta.type.unknown
  uvDensityCount = null;

  /** uvDensities (granny_real32*) */
  @meta.type.objectRef("granny_real32")
  uvDensities = null;

}
