// Source: trinity/trinity/Utilities/GeometryUtils.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/MeshBoundsInfo.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the quarantined pointer-and-count Granny mesh-bounds record that readers replace with detached array-backed data. */
@type.define({ className: "MeshBoundsInfo", family: "utilities" })
export class MeshBoundsInfo extends CjsModel
{

  /** typeName (const char*) */
  @type.objectRef("char")
  typeName = null;

  /** bounds (BoundingBox) */
  @type.rawStruct("BoundingBox")
  bounds = null;

  /** areaCount (granny_int32) */
  @type.unknown
  areaCount = null;

  /** areaInfos (AreaBoundsInfo*) */
  @type.objectRef("AreaBoundsInfo")
  areaInfos = null;

  /** sourceMeshIndex (granny_int32) */
  @type.unknown
  sourceMeshIndex = null;

  /** maxScreenSize (granny_int32) */
  @type.unknown
  maxScreenSize = null;

  /** uvDensityCount (granny_int32) */
  @type.unknown
  uvDensityCount = null;

  /** uvDensities (granny_real32*) */
  @type.objectRef("granny_real32")
  uvDensities = null;

}
