// Source: trinity/trinity/Include/Point.h
// Generated by format-carbon carbon-class --emit. Verify against include/Point.json.
import { meta } from "#schema";

/** Retains the quarantined native integer point helper that adapter boundaries replace with plain x/y records. */
@meta.define({ className: "Point", family: "include" })
export class Point
{

  /** y (int32_t) */
  @meta.type.int32
  y = 0;

  /** x (int32_t) */
  @meta.type.int32
  x = 0;

}
