// Source: trinity/trinity/Include/Point.h
// Generated by format-carbon carbon-class --emit. Verify against include/Point.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the quarantined native integer point helper that adapter boundaries replace with plain x/y records. */
@type.define({ className: "Point", family: "include" })
export class Point extends CjsModel
{

  /** y (int32_t) */
  @type.int32
  y = 0;

  /** x (int32_t) */
  @type.int32
  x = 0;

}
