// Source: trinity/trinity/Include/Tr2Curve.h
// Generated by format-carbon carbon-class --emit. Verify against include/Tr2CurveBase.json.
import { meta } from "#schema";

/** Retains the rejected generic curve-template identity whose unresolved key types are represented by maintained concrete curves. */
@meta.define({ className: "Tr2CurveBase", family: "include" })
export class Tr2CurveBase
{

  /** m_reversed (bool) */
  @meta.type.boolean
  reversed = false;

  /** m_cycle (bool) */
  @meta.type.boolean
  cycle = false;

  /** m_length (float) */
  @meta.type.float32
  length = 0;

  /** m_localTime (float) */
  @meta.type.float32
  localTime = 0;

  /** m_name (std::string) */
  @meta.type.string
  name = "";

  /** m_timeOffset (float) */
  @meta.type.float32
  timeOffset = 0;

  /** m_timeScale (float) */
  @meta.type.float32
  timeScale = 0;

  /** m_startValue (KeyValue) */
  @meta.type.rawStruct("KeyValue")
  startValue = null;

  /** m_currentValue (KeyValue) */
  @meta.type.rawStruct("KeyValue")
  currentValue = null;

  /** m_endValue (KeyValue) */
  @meta.type.rawStruct("KeyValue")
  endValue = null;

  /** m_interpolation (unsigned int) */
  @meta.type.uint32
  interpolation = 0;

  /** m_keys (KeyList) */
  @meta.type.list("Key")
  keys = [];

  /** m_currentKeyIdx (int) */
  @meta.type.int32
  currentKeyIdx = 0;

  /** m_lastKey (Key*) */
  @meta.type.objectRef("Key")
  lastKey = null;

  /** m_nextKey (Key*) */
  @meta.type.objectRef("Key")
  nextKey = null;

  /** m_startOfSegment (float) */
  @meta.type.float32
  startOfSegment = 0;

  /** m_endOfSegment (float) */
  @meta.type.float32
  endOfSegment = 0;

}
