// Source: trinity/trinity/Curves/Tr2CurveScalar.h
// Generated by format-carbon carbon-class --emit. Verify against curves/Tr2CurveRasterizeDestination.json.
import { meta } from "#schema";

/** Retains the native rasterization destination identity consumed as a plain method record by `Tr2CurveScalar`. */
@meta.define({ className: "Tr2CurveRasterizeDestination", family: "curves" })
export class Tr2CurveRasterizeDestination
{

  /** width (uint32_t) */
  @meta.type.uint32
  width = 0;

  /** stride (uint32_t) */
  @meta.type.uint32
  stride = 0;

  /** data (Float_16*) */
  @meta.type.objectRef("Float_16")
  data = null;

}
