// Source: trinity/trinity/Curves/Tr2CurveScalar.h
// Generated by format-carbon carbon-class --emit. Verify against curves/Tr2CurveScalarDefinition.json.
import { meta } from "#schema";

/** Retains the native scalar-curve definition identity consumed as a plain method record by `Tr2CurveScalar`. */
@meta.define({ className: "Tr2CurveScalarDefinition", family: "curves" })
export class Tr2CurveScalarDefinition
{

  /** keys (const Tr2CurveScalarKey*) */
  @meta.type.objectRef("Tr2CurveScalarKey")
  keys = null;

  /** keyCount (uint32_t) */
  @meta.type.uint32
  keyCount = 0;

  /** extrapolationBefore (Tr2CurveExtrapolation::Type - enum Tr2CurveExtrapolation) */
  @meta.type.int32
  @meta.type.enum("Tr2CurveExtrapolation")
  extrapolationBefore = 0;

  /** extrapolationAfter (Tr2CurveExtrapolation::Type - enum Tr2CurveExtrapolation) */
  @meta.type.int32
  @meta.type.enum("Tr2CurveExtrapolation")
  extrapolationAfter = 0;

  static Tr2CurveExtrapolation = Object.freeze({
    CLAMP: 0,
    CYCLE: 1,
    MIRROR: 2,
    LINEAR: 3,
  });

}
