// Source: trinity/trinity/Include/ITr2DebugRenderer2.h
// Generated by format-carbon carbon-class --emit. Verify against include/Tr2DebugObjectReference.json.
import { meta } from "#schema";

/** Retains the native debug-renderer reference identity that engine adapters replace with plain reference records. */
@meta.define({ className: "Tr2DebugObjectReference", family: "include" })
export class Tr2DebugObjectReference
{

  /** m_object (IRootPtr) */
  @meta.type.objectRef("IRoot")
  object = null;

  /** m_area (uint32_t) */
  @meta.type.uint32
  area = 0;

}
