// Source: trinity/trinity/Include/ITr2DebugRenderer2.h
// Generated by format-carbon carbon-class --emit. Verify against include/Tr2DebugColor.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the native debug-renderer color identity that engine adapters replace with plain value records. */
@type.define({ className: "Tr2DebugColor", family: "include" })
export class Tr2DebugColor extends CjsModel
{

  /** m_color (uint32_t) */
  @type.uint32
  color = 0;

  /** m_zFailColor (uint32_t) */
  @type.uint32
  zFailColor = 0;

  /** m_colorSelected (uint32_t) */
  @type.uint32
  colorSelected = 0;

  /** m_zFailColorSelected (uint32_t) */
  @type.uint32
  zFailColorSelected = 0;

}
