// Source: trinity/trinity/Include/ITr2DebugRenderer2.h
// Generated by format-carbon carbon-class --emit. Verify against include/Tr2DebugObjectReference.json.
import { type } from "#schema";

/** Retains the native debug-renderer reference identity that engine adapters replace with plain reference records. */
@type.define({ className: "Tr2DebugObjectReference", family: "include" })
export class Tr2DebugObjectReference
{

  /** m_object (IRootPtr) */
  @type.objectRef("IRoot")
  object = null;

  /** m_area (uint32_t) */
  @type.uint32
  area = 0;

}
