// Source: trinity/trinity/Include/Tr2Curve.h
// Generated by format-carbon carbon-class --emit. Verify against curves/Tr2Key.json.
import { meta } from "#schema";

/** Retains the rejected generic key-template identity whose unresolved value type is represented by maintained concrete key classes. */
@meta.define({ className: "Tr2Key", family: "curves" })
export class Tr2Key
{

  /** m_time (float) */
  @meta.type.float32
  time = 0;

  /** m_value (T) */
  @meta.type.rawStruct("T")
  value = null;

  /** m_interpolation (Interpolation - enum Interpolation) */
  @meta.type.int32
  @meta.type.enum("Interpolation")
  interpolation = 0;

  static Interpolation = Object.freeze({
    CONSTANT: 0,
    LINEAR: 1,
    HERMITE: 2,
    CATMULLROM: 3,
    SPHERICAL_LINEAR: 4,
    SPHERICAL_QUADRANGLE: 5,
  });

}
