// Source: trinity/trinity/Eve/EveOccluder.h
// Generated by format-carbon carbon-class --emit. Verify against eve/scene/Tr2OcclusionBuffer.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the native GPU occlusion-buffer service identity whose allocation and effect processing belong to a renderer backend. */
@type.define({ className: "Tr2OcclusionBuffer", family: "eve/scene" })
export class Tr2OcclusionBuffer extends CjsModel
{

  /** m_management (Tr2EffectPtr) */
  @type.objectRef("Tr2Effect")
  management = null;

  /** m_buffer (Tr2GpuBufferPtr) */
  @type.objectRef("Tr2GpuBuffer")
  buffer = null;

  /** m_free (std::vector<uint32_t>) */
  @type.list("uint32_t")
  free = [];

  /** m_clear (std::vector<uint32_t>) */
  @type.list("uint32_t")
  clear = [];

  /** m_size (uint32_t) */
  @type.uint32
  size = 0;

  /** ELEMENT_SIZE (static const uint32_t) */
  @type.unknown
  ELEMENT_SIZE = 13;

}
