// Source: trinity/trinity/Particle/Tr2ParticleElementDeclaration.h
// Generated by format-carbon carbon-class --emit. Verify against particle/Tr2ParticleStreamIterator.json.
import { meta } from "#schema";

/** Retains the native typed-pointer iterator identity superseded by typed-array indexing in CPU particle simulation. */
@meta.define({ className: "Tr2ParticleStreamIterator", family: "particle" })
export class Tr2ParticleStreamIterator
{

  /** m_stride (m_data +=) */
  @meta.type.unknown
  stride = null;

  /** offset (m_data += m_stride *) */
  @meta.type.objectRef("m_data += m_stride")
  offset = null;

  /** m_data (float*) */
  @meta.type.objectRef("float")
  data = null;

}
