// Source: trinity/trinity/Particle/Tr2ParticleElementDeclaration.h
// Generated by format-carbon carbon-class --emit. Verify against particle/Tr2ParticleStreamIterator.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the native typed-pointer iterator identity superseded by typed-array indexing in CPU particle simulation. */
@type.define({ className: "Tr2ParticleStreamIterator", family: "particle" })
export class Tr2ParticleStreamIterator extends CjsModel
{

  /** m_stride (m_data +=) */
  @type.unknown
  stride = null;

  /** offset (m_data += m_stride *) */
  @type.objectRef("m_data += m_stride")
  offset = null;

  /** m_data (float*) */
  @type.objectRef("float")
  data = null;

}
