// Source: trinity/trinity/Include/Rect.h
// Generated by format-carbon carbon-class --emit. Verify against include/Tr2Rect.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Tr2Rect (include) - generated from schema shapeHash 48e5ca2a.... */
@type.define({ className: "Tr2Rect", family: "include" })
export class Tr2Rect extends CjsModel
{

  /** top (int32_t) */
  @type.int32
  top = 0;

  /** right (int32_t) */
  @type.int32
  right = 0;

  /** bottom (int32_t) */
  @type.int32
  bottom = 0;

  /** left (int32_t) */
  @type.int32
  left = 0;

}
