// Source: trinity/trinity/Include/Rect.h
// Generated by format-carbon carbon-class --emit. Verify against include/Tr2Rect.json.
import { meta } from "#schema";

/** Retains the quarantined native integer rectangle helper that adapter boundaries replace with plain edge records. */
@meta.define({ className: "Tr2Rect", family: "include" })
export class Tr2Rect
{

  /** top (int32_t) */
  @meta.type.int32
  top = 0;

  /** right (int32_t) */
  @meta.type.int32
  right = 0;

  /** bottom (int32_t) */
  @meta.type.int32
  bottom = 0;

  /** left (int32_t) */
  @meta.type.int32
  left = 0;

}
