// Source: trinity/trinity/Raytracing/Tr2RaytracingGeometry.h
// Generated by format-carbon carbon-class --emit. Verify against raytracing/Tr2RaytracingMeshArea.json.
import { meta } from "#schema";

/** Retains the native per-area acceleration-structure helper identity whose state belongs to a ray-tracing engine backend. */
@meta.define({ className: "Tr2RaytracingMeshArea", family: "raytracing" })
export class Tr2RaytracingMeshArea
{

  /** m_areaIndex (uint32_t) */
  @meta.type.uint32
  areaIndex = 0;

  /** m_blas (Tr2RtBottomLevelAccelerationStructureAL) */
  @meta.type.rawStruct("Tr2RtBottomLevelAccelerationStructureAL")
  blas = null;

  /** m_blasOutdated (bool) */
  @meta.type.boolean
  blasOutdated = false;

  /** true (m_blasOutdated =) */
  @meta.type.unknown
  true = null;

}
