// Source: trinity/trinity/Include/TriColor.h
// Generated by format-carbon carbon-class --emit. Verify against trinityCore/TriColor.json.
import { meta } from "#schema";

/** Retains the retired Blue/Python color wrapper identity superseded by runtime vec4 math. */
@meta.define({ className: "TriColor", family: "trinityCore" })
export class TriColor
{

  /** r (unknown) [READWRITE, PERSIST] */
  @meta.blue.persist
  @meta.type.unknown
  r = null;

  /** g (unknown) [READWRITE, PERSIST] */
  @meta.blue.persist
  @meta.type.unknown
  g = null;

  /** b (unknown) [READWRITE, PERSIST] */
  @meta.blue.persist
  @meta.type.unknown
  b = null;

  /** a (float) [READWRITE, PERSIST] */
  @meta.blue.persist
  @meta.type.float32
  a = 0;

  /** Carbon method __init__ -> Py__init__ (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @meta.blue.method
  @meta.notImplemented
  __init__(...args)
  {
    throw new Error("TriColor.__init__ is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetRGB -> PySetRGB (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @meta.blue.method
  @meta.notImplemented
  SetRGB(...args)
  {
    throw new Error("TriColor.SetRGB is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetHSV -> PySetHSV (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @meta.blue.method
  @meta.notImplemented
  SetHSV(...args)
  {
    throw new Error("TriColor.SetHSV is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetVector -> PySetVector (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @meta.blue.method
  @meta.notImplemented
  SetVector(...args)
  {
    throw new Error("TriColor.SetVector is not implemented in CarbonEngineJS.");
  }

  /** Carbon method FromInt -> PyFromInt (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  FromInt(...args)
  {
    throw new Error("TriColor.FromInt is not implemented in CarbonEngineJS.");
  }

  /** Carbon method AsInt -> PyAsInt (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  AsInt(...args)
  {
    throw new Error("TriColor.AsInt is not implemented in CarbonEngineJS.");
  }

  /** Carbon method GetHSV -> PyGetHSV (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  GetHSV(...args)
  {
    throw new Error("TriColor.GetHSV is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Scale (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Scale(...args)
  {
    throw new Error("TriColor.Scale is not implemented in CarbonEngineJS.");
  }

}
