// Source: trinity/trinity/Include/TriMath.h
// Generated by format-carbon carbon-class --emit. Verify against include/TriPerlinNoise.json.
import { meta } from "#schema";

/** Retains the incomplete scanner model for Carbon's seeded-noise utility, whose runtime behavior lives in maintained math functions. */
@meta.define({ className: "TriPerlinNoise", family: "include" })
export class TriPerlinNoise
{

  /** TABLE_SIZE (static constexpr int32_t) */
  @meta.type.unknown
  TABLE_SIZE = 256;

  /** TABLE_MASK (static constexpr int32_t) */
  @meta.type.unknown
  TABLE_MASK = null;

}
