// Source: trinity/trinity/Include/TriMath.h
// Generated by format-carbon carbon-class --emit. Verify against include/TriPerlinNoise.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** TriPerlinNoise (include) - generated from schema shapeHash a520344a.... */
@type.define({ className: "TriPerlinNoise", family: "include" })
export class TriPerlinNoise extends CjsModel
{

  /** TABLE_SIZE (static constexpr int32_t) */
  @type.unknown
  TABLE_SIZE = 256;

  /** TABLE_MASK (static constexpr int32_t) */
  @type.unknown
  TABLE_MASK = null;

}
