// Source: trinity/trinity/Include/TriVector.h
// Generated by format-carbon carbon-class --emit. Verify against trinityCore/TriVector.json.
import { meta } from "#schema";

/** Retains the retired Blue/Python vector wrapper identity superseded by runtime vec3 math. */
@meta.define({ className: "TriVector", family: "trinityCore" })
export class TriVector
{

  /** x (unknown) [READWRITE, PERSIST] */
  @meta.blue.persist
  @meta.type.unknown
  x = null;

  /** y (unknown) [READWRITE, PERSIST] */
  @meta.blue.persist
  @meta.type.unknown
  y = null;

  /** z (unknown) [READWRITE, PERSIST] */
  @meta.blue.persist
  @meta.type.unknown
  z = null;

  /** Carbon method TransformCoord -> PyTransformCoord (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  TransformCoord(...args)
  {
    throw new Error("TriVector.TransformCoord is not implemented in CarbonEngineJS.");
  }

  /** Carbon method TransformNormal -> PyTransformNormal (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  TransformNormal(...args)
  {
    throw new Error("TriVector.TransformNormal is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Lerp -> PyLerp (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Lerp(...args)
  {
    throw new Error("TriVector.Lerp is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Maximize -> PyMaximize (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Maximize(...args)
  {
    throw new Error("TriVector.Maximize is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Minimize -> PyMinimize (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Minimize(...args)
  {
    throw new Error("TriVector.Minimize is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Subtract -> PySubtract (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Subtract(...args)
  {
    throw new Error("TriVector.Subtract is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Project -> PyProject (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Project(...args)
  {
    throw new Error("TriVector.Project is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Unproject -> PyUnproject (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Unproject(...args)
  {
    throw new Error("TriVector.Unproject is not implemented in CarbonEngineJS.");
  }

  /** Carbon method __init__ -> SetXYZ (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @meta.blue.method
  @meta.notImplemented
  __init__(...args)
  {
    throw new Error("TriVector.__init__ is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Add -> PyAdd (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Add(...args)
  {
    throw new Error("TriVector.Add is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Cross -> PyCross (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Cross(...args)
  {
    throw new Error("TriVector.Cross is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Dot -> PyDot (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Dot(...args)
  {
    throw new Error("TriVector.Dot is not implemented in CarbonEngineJS.");
  }

  /** Carbon method DotProduct -> PyDotProduct (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  DotProduct(...args)
  {
    throw new Error("TriVector.DotProduct is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Normalize (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Normalize(...args)
  {
    throw new Error("TriVector.Normalize is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Length (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Length(...args)
  {
    throw new Error("TriVector.Length is not implemented in CarbonEngineJS.");
  }

  /** Carbon method LengthSq (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  LengthSq(...args)
  {
    throw new Error("TriVector.LengthSq is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Scale (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  Scale(...args)
  {
    throw new Error("TriVector.Scale is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetXYZ (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  SetXYZ(...args)
  {
    throw new Error("TriVector.SetXYZ is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetCrossProduct -> PySetCrossProduct (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  SetCrossProduct(...args)
  {
    throw new Error("TriVector.SetCrossProduct is not implemented in CarbonEngineJS.");
  }

  /** Carbon method TransformQuaternion -> PyTransformQuaternion (MAP_METHOD_AND_WRAP). */
  @meta.blue.method
  @meta.notImplemented
  TransformQuaternion(...args)
  {
    throw new Error("TriVector.TransformQuaternion is not implemented in CarbonEngineJS.");
  }

}
