// Source: trinity/trinity/Utilities/Vector3d.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/Vector3d.json.
import { type } from "#schema";
import { CjsModel } from "#model";

/** Retains the native double-precision three-component value identity represented at runtime by numeric arrays or `Float64Array` values. */
@type.define({ className: "Vector3d", family: "utilities" })
export class Vector3d extends CjsModel
{

  /** d (x *=) */
  @type.unknown
  d = null;

  /** dDiv (x *=) */
  @type.unknown
  dDiv = null;

  /** norm (norm = 1.0 /) */
  @type.unknown
  norm = null;

  /** xt (x =) */
  @type.unknown
  xt = null;

  /** yt (y =) */
  @type.unknown
  yt = null;

  /** zt (z =) */
  @type.unknown
  zt = null;

  /** x (double) */
  @type.float64
  x = 0;

  /** y (double) */
  @type.float64
  y = 0;

  /** z (double) */
  @type.float64
  z = 0;

  /** f (x =) */
  @type.unknown
  f = null;

}
