// Source: trinity/trinity/Utilities/Vector3d.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/Vector3d.json.
import { meta } from "#schema";

/** Retains the native double-precision three-component value identity represented at runtime by numeric arrays or `Float64Array` values. */
@meta.define({ className: "Vector3d", family: "utilities" })
export class Vector3d
{

  /** d (x *=) */
  @meta.type.unknown
  d = null;

  /** dDiv (x *=) */
  @meta.type.unknown
  dDiv = null;

  /** norm (norm = 1.0 /) */
  @meta.type.unknown
  norm = null;

  /** xt (x =) */
  @meta.type.unknown
  xt = null;

  /** yt (y =) */
  @meta.type.unknown
  yt = null;

  /** zt (z =) */
  @meta.type.unknown
  zt = null;

  /** x (double) */
  @meta.type.float64
  x = 0;

  /** y (double) */
  @meta.type.float64
  y = 0;

  /** z (double) */
  @meta.type.float64
  z = 0;

  /** f (x =) */
  @meta.type.unknown
  f = null;

}
