// Source: trinity/trinity/Utilities/Vector4d.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/Vector4d.json.
import { meta } from "#schema";

/** Retains the native double-precision four-component value identity represented at runtime by numeric arrays or `Float64Array` values. */
@meta.define({ className: "Vector4d", family: "utilities" })
export class Vector4d
{

  /** d (x *=) */
  @meta.type.unknown
  d = null;

  /** dDiv (x *=) */
  @meta.type.unknown
  dDiv = null;

  /** x (double) */
  @meta.type.float64
  x = 0;

  /** y (double) */
  @meta.type.float64
  y = 0;

  /** z (double) */
  @meta.type.float64
  z = 0;

  /** w (double) */
  @meta.type.float64
  w = 0;

  /** f (x =) */
  @meta.type.unknown
  f = null;

}
