import definitions from "./black-schema-v1-2026-09-29.json" with { type: "json" };

/**
 * Black class and enum definitions from the newest dated snapshot.
 *
 * Dated snapshots are never edited in place: a new Carbon scan writes a new
 * file, and the tools-core `cjs-carbon-schema --black-module` option re-points
 * the import above at the newest one. It rewrites only that import, so update
 * this provenance note with it.
 *
 * Current snapshot (2026-09-29 Carbon scan): generated by tools-core commit
 * 687a2920b4aba5d0a09fdc0888f8d268631e26ae. It differs from 2026-09-25
 * only in Tr2PostProcessAttributes: Carbon's 56 persisted Enabled/value
 * pairs are expanded from POSTPROCESSATTRIBUTE_DEFINE and its enum variant.
 * SHA-256 6A27B1AC58CF293FBFFABC53181C0B6D89B822867ABA726F1B7BDACAA2E824DB.
 */


export const schema = definitions.schema;
export const version = definitions.version;
export const generatedAt = definitions.generatedAt;
export const enums = definitions.enums;
// Explicit transport declarations supplement native custom-block macros, which
// identify a wire block but cannot state the JavaScript data type. The dated
// donor snapshot remains unchanged.
export const classes = {
    ...definitions.classes,
    EveSOFDataDecalIndexBuffer: { ...definitions.classes.EveSOFDataDecalIndexBuffer, indexBuffer: "uint32Array" },
    Tr2ActionPython: { ...definitions.classes.Tr2ActionPython, state: { type: "custom", name: "Tr2ActionPython.state" } }
};

export { definitions };
export default classes;
