import definitions from "./black-schema-v1-2026-09-25.json" with { type: "json" };

/**
 * Black class and enum definitions from the newest dated snapshot.
 *
 * Dated snapshots are never edited in place: a new Carbon scan writes a new
 * file, and the tools-core `cjs-carbon-schema --black-module` option re-points
 * the import above at the newest one. It rewrites only that import, so update
 * this provenance note with it.
 *
 * Current snapshot (2026-09-25 Carbon scan): generated by tools-core with
 * the Tr2CurveScalar and Tr2CurveQuaternion key layouts added to its field
 * resolutions (Carbon's Tr2CurveScalarKeyDef / Tr2CurveQuaternionKeyDef).
 * It differs from 2026-09-19 in those two classes only. SHA-256
 * F7E6951866C8565EE51936768A64EAB52C4C1448C3988E70B350DAFC8F31FB7A.
 */


export const schema = definitions.schema;
export const version = definitions.version;
export const generatedAt = definitions.generatedAt;
export const enums = definitions.enums;
export const classes = definitions.classes;

export { definitions };
export default classes;
