import definitions from "./black-schema-v1-2026-09-19.json" with { type: "json" };

/**
 * Black class and enum definitions from the newest dated snapshot.
 *
 * Dated snapshots are never edited in place: a new Carbon scan writes a new
 * file, and the tools-core `cjs-carbon-schema --black-module` option re-points
 * the import above at the newest one. It rewrites only that import, so update
 * this provenance note with it.
 *
 * Current snapshot (2026-09-19 Carbon scan): generated by tools-core
 * revision d8c20bb, landed in runtime revision 2c2b8c9f, SHA-256
 * 0A4EBE699C9055C6132A41F6F709C2CC4BF80E928DC958DE13C1AF1F45F19A19.
 */


export const schema = definitions.schema;
export const version = definitions.version;
export const generatedAt = definitions.generatedAt;
export const enums = definitions.enums;
export const classes = definitions.classes;

export { definitions };
export default classes;
