import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const banner = /Generated by format-carbon/u;

function read(relativePath)
{
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function javascriptFiles(directory)
{
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry =>
  {
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) return javascriptFiles(target);
    return entry.isFile() && entry.name.endsWith(".js") ? [ target ] : [];
  });
}

test("generated character classes are isolated from maintained Trinity source", () =>
{
  const generated = [
    "src/character/generated/interior/enums.js",
    "src/character/generated/interior/Tr2InteriorPerObjectLightData.js",
    "src/character/generated/interior/Tr2InteriorPerObjectVSData.js",
    "src/character/generated/interior/Tr2PerObjectParticleVSData.js"
  ];

  for (const relativePath of generated)
  {
    assert.match(read(relativePath), banner, `${relativePath} retains generator provenance`);
  }

  for (const file of javascriptFiles(path.join(root, "src", "character", "trinity")))
  {
    assert.doesNotMatch(fs.readFileSync(file, "utf8"), banner, `${file} is maintained source`);
  }
});
