// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObject/Utils/EveDistributionMethods/DistributionPlacementGenerators/EveDistributionPlacementGeneratorParentLocators.h
// Generated by format-carbon carbon-class --emit. Verify against eve/distribution/placement/EveDistributionPlacementGeneratorParentLocators.json.
import { carbon, impl, io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { InitialPlacement } from "../attributeModifiers/InitialPlacement.js";
import { PlacementDataWithIdentifier } from "../../PlacementDataWithIdentifier.js";

/** EveDistributionPlacementGeneratorParentLocators (eve/distribution/placement) - generated from schema shapeHash ebb2456a.... */
@type.define({ className: "EveDistributionPlacementGeneratorParentLocators", family: "eve/distribution/placement" })
export class EveDistributionPlacementGeneratorParentLocators extends CjsModel
{

  // Carbon's structure-list notification drives this regeneration state.
  #regenerated = false;

  #requestRegeneration = false;

  #locators = null;

  #parent = null;

  #locatorSetName = null;

  /** m_locatorSetName (BlueSharedString) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.string
  locatorSetName = "damage";

  /**
   * Appends one placement per locator of the parent space object's named locator set, copying position, direction, scale and bone index; appends nothing until an update has resolved that set.
   *
   * @param placements Caller-owned pool array that is appended to.
   * @param trackingID Mutable counter shared across all generators; each placement consumes one unique id from it.
   */
  @carbon.method
  @impl.adapted
  GetInitialPlacements(placements, trackingID)
  {
    this.#requestRegeneration = false;
    if (!this.#locators)
    {
      return;
    }

    for (const locator of this.#locators)
    {
      const data = new PlacementDataWithIdentifier();
      data.initialTranslation.set(locator.position);
      data.initialRotation.set(locator.direction);
      data.initialScale.set(locator.scale);
      data.boneIndex = locator.boneIndex;
      data.uniqueID = trackingID.value++;

      const placement = new InitialPlacement();
      placement.placement = data;
      placement.timeOutDuration = 0;
      placements.push(placement);
    }
  }

  /**
   * Reports whether a locator set has just been resolved from the parent and the
   * pool therefore needs rebuilding.
   */
  @carbon.method
  @impl.implemented
  IsRequestingRegeneration()
  {
    return this.#requestRegeneration;
  }

  /**
   * Resolves the named locator set from the space-object parent carried by the
   * update params, re-resolving whenever the parent or the set name changes, and
   * requests regeneration once locators are found.
   */
  @carbon.method
  @impl.adapted
  UpdateSyncronous(_updateContext, params, _owner)
  {
    const parent = params.spaceObjectParent;
    const locatorSetName = String(this.locatorSetName ?? "");
    if (parent !== this.#parent || locatorSetName !== this.#locatorSetName)
    {
      this.#parent = parent;
      this.#locatorSetName = locatorSetName;
      this.#locators = null;
      this.#regenerated = false;
    }

    if (!this.#regenerated && parent)
    {
      const locators = parent.GetLocatorsForSet(locatorSetName);
      this.#locators = locators;
      if (locators)
      {
        this.#regenerated = true;
        this.#requestRegeneration = true;
      }
    }
  }

  /**
   * Invalidates the resolved locator set after an authored change so the next
   * update re-reads it.
   */
  @carbon.method
  @impl.adapted
  OnModified(_options = {})
  {
    this.#regenerated = false;
    return true;
  }

  /**
   * Invalidates the resolved locator set so the next update re-reads it from the
   * parent.
   */
  @carbon.method
  @impl.adapted
  @impl.reason("JavaScript retains explicit invalidation state in place of native structure-list notifier ownership.")
  OnStructureListModified(_event, _item, _index, _list)
  {
    this.#regenerated = false;
  }

}
