// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
// Maintained as runtime-trinity's backend-neutral turret constant-data contract.
//   trinity/trinity/Eve/Turret/EveTurretSet.h
// Generated by format-carbon carbon-class --emit. Verify against eve/attachment/turrets/EveTurretSetVSData.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { mat4 } from "@carbonenginejs/runtime-utils/mat4";
import { quat } from "@carbonenginejs/runtime-utils/quat";
import { vec4 } from "@carbonenginejs/runtime-utils/vec4";

/** EveTurretSetVSData (eve/attachment/turrets) - generated from schema shapeHash 9b992797.... */
@type.define({ className: "EveTurretSetVSData", family: "eve/attachment/turrets" })
export class EveTurretSetVSData extends CjsModel
{

  /** m_baseCutoffData (Vector4) */
  @type.vec4
  baseCutoffData = vec4.create();

  /** m_turretSetData (Vector4) */
  @type.vec4
  turretSetData = vec4.create();

  /** m_shipMatrix (Matrix) */
  @type.mat4
  shipMatrix = mat4.create();

  /** m_prevShipMatrix (Matrix) */
  @type.mat4
  prevShipMatrix = mat4.create();

  /** m_currentBoneOffset (uint32_t) */
  @type.uint32
  currentBoneOffset = 0;

  /** m_prevBoneOffset (uint32_t) */
  @type.uint32
  prevBoneOffset = 0;

  /** _unused (uint32_t[2]) - Carbon's explicit pad; never written. */
  @type.array("uint32")
  _unused = [0, 0];

  /** m_turretTranslation (Vector4[EVE_MAX_TURRETS_PER_SET]) */
  @type.array("vec4")
  turretTranslation = Array.from(
    { length: EveTurretSetVSData.TURRET_COUNT },
    () => vec4.create()
  );

  /** m_turretRotation (Quaternion[EVE_MAX_TURRETS_PER_SET]) */
  @type.array("quat")
  turretRotation = Array.from(
    { length: EveTurretSetVSData.TURRET_COUNT },
    () => quat.create()
  );

  /** EveTurretSet.h:43 - `EVE_MAX_TURRETS_PER_SET`. */
  static TURRET_COUNT = 24;

}
